import orcaProfiles from '../data/orca-profiles.json'
import type { OrcaConfig, PassthroughConfig, SlicePreset } from '../types'
import { mergeConfigLayers } from './config-layers'

// orcaProfiles is generated by scripts/fetch-orca-profiles.ts from
// OrcaSlicer's own bundled profile tree (resources/profiles/<Vendor>/...),
// resolving each profile's `inherits` chain. Re-fetch with:
//   npx tsx scripts/fetch-orca-profiles.ts
export const PRESETS: SlicePreset[] = orcaProfiles.qualityPresets as SlicePreset[]

export const FILAMENT_PRESETS: Record<string, Partial<OrcaConfig>> = orcaProfiles.filamentPresets

// bed_size_x/y and printable_height are real values from OrcaSlicer's own
// bundled profiles (resources/profiles/<Vendor>/machine/*.json) — our
// headless WASM build ships none of these, so the web UI's presets are the
// only source of truth for them. printable_height in particular used to be
// missing entirely, silently falling back to the *engine's* generic
// FullPrintConfig default of 100mm (PrintConfig.cpp) — well under any of
// these printers' real Z height, so any model taller than 100mm failed
// "exceeds the maximum build volume height" validation regardless of which
// printer was selected.
export const PRINTER_PRESETS: Record<string, Partial<OrcaConfig>> = orcaProfiles.printerPresets

// UI display fallbacks for config fields a preset may leave unset. Display
// only — deliberately NOT merged into the engine config (an unset field must
// keep falling back to the engine's own default, which may differ). Having
// one table keeps every surface (settings inputs, config summary, 3D bed
// viewers) quoting the same number instead of each hardcoding its own.
//
// For every field the engine also has, the value here MUST equal that
// engine default (PrintConfig.cpp's set_default_value), and new entries
// should be checked against it. Not cosmetic: because these are display-only,
// a field left unset is absent from exportOrcaProfileJson()'s output too —
// desktop OrcaSlicer then resolves it from the same engine default, so an
// entry that disagrees means the panel shows one number while both the local
// slice and the exported preset silently use another. wall_loops sat at 3
// against the engine's 2 for exactly that reason.
export const DISPLAY_DEFAULTS = {
  printer_model: 'Generic',
  nozzle_diameter: 0.4,
  bed_size_x: 256,
  bed_size_y: 256,
  printable_height: 100,
  bed_shape: 'rectangle',
  filament_type: 'PLA',
  nozzle_temperature: 220,
  bed_temperature: 60,
  layer_height: 0.2,
  initial_layer_print_height: 0.2,
  top_shell_layers: 4,
  bottom_shell_layers: 3,
  wall_loops: 2,
  wall_generator: 'arachne',
  sparse_infill_density: 15,
  sparse_infill_pattern: 'grid',
  default_speed: 100,
  outer_wall_speed: 60,
  initial_layer_speed: 30,
  travel_speed: 150,
  seam_position: 'aligned',
  fuzzy_skin: 'none',
  fuzzy_skin_thickness: 0.3,
  fuzzy_skin_point_dist: 0.8,
  // Adaptive-layer-height quality/speed factor (see OrcaConfig). The toggle
  // itself has no entry — like enable_ironing / remove_mixed_temp_restriction
  // it defaults off via an inline `?? false`; only the slider needs a value.
  adaptive_layer_height_quality: 0.5,
  enable_support: false,
  support_type: 'normal(auto)',
  brim_width: 0,
  brim_type: 'auto_brim',
  skirt_loops: 1,
  skirt_distance: 2,
  raft_layers: 0,
  // Prime-tower width matches the engine default (PrintConfig.cpp
  // prime_tower_width). enable_prime_tower is deliberately absent: its engine
  // default is off, but withFilamentSlots() flips the *effective* default to
  // on for a multi-slot config, and the panel toggle only ever shows in that
  // context — so it reads PRIME_TOWER_DEFAULT_ENABLED, not this table. Putting
  // false here would make the toggle render off while the slice ran with a
  // tower.
  prime_tower_width: 60,
} as const satisfies OrcaConfig

/**
 * Split the config's filament_type into the individual material names it
 * mentions, for display only (ConfigSummary's "Material" row) — an imported
 * profile can carry something like "PLA;PETG" and listing both reads better
 * than printing the raw string.
 *
 * Explicitly NOT a slot count. It's tempting to read one entry here as one
 * AMS slot, and an earlier revision of this file claimed exactly that, but
 * it is false: measured against OrcaSlicer 2.4.2, "PLA;PETG" resolves to a
 * single filament (`['PLA']`), "PLA,PETG" to `['PLA,PETG']`, and even a JSON
 * array `["PLA","PETG"]` to `['PLA']`. The engine's filament count is the
 * number of separate filament *presets* it was given, which this app does
 * not model — see issue #155 before using this for anything but text.
 */
export function filamentSlots(config: OrcaConfig): string[] {
  return String(config.filament_type ?? DISPLAY_DEFAULTS.filament_type)
    .split(/[;,]/)
    .map((entry) => entry.trim())
    .filter(Boolean)
}

/**
 * Default slot colours. `filament_colour` is not cosmetic here: the engine
 * derives its filament *count* from `filament_colour.values.size()`
 * (ToolOrdering.cpp's `number_of_extruders`), which then sizes the flush
 * matrix. A slot without a colour is a slot the engine does not know exists.
 */
const SLOT_COLOURS = ['#F5A623', '#4A90D9', '#7ED321', '#D0021B', '#9013FE', '#50E3C2', '#F8E71C', '#B8E986']

/**
 * Upper bound on filament slots offered in the UI — one per SLOT_COLOURS entry,
 * comfortably above the 4 slots of a single AMS unit. The engine imposes no
 * limit of its own, but each extra slot grows the flush matrix quadratically.
 */
export const MAX_FILAMENT_SLOTS = SLOT_COLOURS.length

/** Volume purged when switching between two different filaments, in mm³. */
const FLUSH_VOLUME = 280

/**
 * Whether a multi-slot config gets a prime (wipe) tower unless something says
 * otherwise. OrcaSlicer's own engine default is *off* (PrintConfig.cpp
 * `enable_prime_tower`), which is the #163 bug: #160 configures the per-filament
 * flush volumes but, with no tower, the purge those volumes describe has nowhere
 * to go. A multi-material plate wants one, so default it on — the settings-panel
 * toggle and any imported profile still override this (see primeTowerEnabled).
 */
export const PRIME_TOWER_DEFAULT_ENABLED = true

/**
 * Filament diameter for a slot nothing declares one for, in mm — the engine's
 * own PrintConfig.cpp default, and what every FFF profile this app ships is
 * built around. Only a fallback: an imported profile carrying 2.85 keeps it.
 */
const DEFAULT_FILAMENT_DIAMETER = '1.75'
const DEFAULT_FILAMENT_EXTRUDER_VARIANT = 'Direct Drive Standard'

export type ImportedProfileType = 'machine' | 'filament' | 'process' | 'print'

/** One locally selected OrcaSlicer JSON file, before it is merged with its companions. */
export interface ImportedProfileFile {
  name: string
  type: ImportedProfileType
  settings: Partial<OrcaConfig>
  /** The parent name is not an engine setting, but helps recover a useful
   * printer model from machine profiles whose leaf file omits printer_model. */
  inherits?: string
}

/** The effective config produced by importing one or more profile files. */
export interface ImportedProfileSet {
  name: string
  sourceNames: string[]
  profileTypes: ImportedProfileType[]
  settings: Partial<OrcaConfig>
}

/**
 * How many physical nozzles the chosen printer has. Real multi-nozzle machines
 * carry a `nozzle_diameter` array (a Bambu Lab H2D has two); everything else
 * is a single nozzle feeding however many filament slots.
 */
export function physicalNozzleCount(config: Partial<OrcaConfig> | undefined): number {
  const raw = config?._passthrough?.nozzle_diameter
  return Array.isArray(raw) && raw.length > 0 ? raw.length : 1
}

/**
 * The filament names a parsed/imported config declares, in engine order.
 * Unlike filamentSlots(), this is an actual slot source: arrays are the shape
 * OrcaSlicer uses for separate filament presets, while a joined scalar is only
 * a best-effort fallback for older hand-written files.
 */
export function importedFilamentTypes(config: Partial<OrcaConfig>): string[] {
  const raw = config._passthrough?.filament_type
  if (Array.isArray(raw))
    return raw
      .map(String)
      .map((v) => v.trim())
      .filter(Boolean)
  const value = typeof raw === 'string' ? raw : config.filament_type
  if (typeof value !== 'string' || !value.trim()) return []
  return value
    .split(/[;,]/)
    .map((v) => v.trim())
    .filter(Boolean)
}

/**
 * Infer the category of a leaf profile when OrcaSlicer omitted its optional
 * `type` metadata. The files in a user's `user/<vendor>/machine`, `process`
 * and `filament` folders are intentionally self-contained JSON documents, and
 * the browser File API does not expose their parent directory. Real backups
 * therefore need a content-based fallback rather than being treated as a
 * generic print profile.
 *
 * This is deliberately leaf-oriented: a complete project/export containing
 * machine, process and filament options is not a substitute for selecting its
 * separate preset files. Explicit `type` metadata still wins in the UI.
 */
export function inferImportedProfileType(
  profile: Pick<ImportedProfileFile, 'name' | 'settings' | 'inherits'>,
): ImportedProfileType {
  const settings = profile.settings
  const passthroughKeys = new Set(Object.keys(settings._passthrough ?? {}))
  const hasAny = (...keys: string[]) => keys.some((key) => passthroughKeys.has(key))

  if (
    settings.printer_model !== undefined ||
    settings.nozzle_diameter !== undefined ||
    settings.bed_size_x !== undefined ||
    settings.bed_size_y !== undefined ||
    settings.printable_height !== undefined ||
    hasAny(
      'printable_area',
      'machine_start_gcode',
      'machine_end_gcode',
      'machine_pause_gcode',
      'machine_max_speed_x',
      'machine_max_speed_y',
      'machine_max_speed_z',
      'machine_max_speed_e',
      'machine_max_acceleration_x',
      'machine_max_acceleration_y',
      'machine_max_acceleration_z',
      'machine_max_acceleration_e',
    ) ||
    /\s\d+(?:\.\d+)?\s+nozzle$/i.test(profile.inherits ?? '')
  ) {
    return 'machine'
  }

  if (
    settings.filament_type !== undefined ||
    settings.nozzle_temperature !== undefined ||
    settings.bed_temperature !== undefined ||
    settings.fan_min_speed !== undefined ||
    hasAny(
      'filament_type',
      'filament_colour',
      'filament_diameter',
      'filament_flow_ratio',
      'filament_max_volumetric_speed',
      'filament_start_gcode',
      'filament_end_gcode',
      'filament_cost',
      'filament_density',
      'hot_plate_temp',
      'hot_plate_temp_initial_layer',
      'nozzle_temperature',
      'nozzle_temperature_initial_layer',
      'pressure_advance',
      'enable_pressure_advance',
    ) ||
    /\b(?:PLA|PETG|ABS|ASA|TPU|TPE|Nylon|PA(?:[-_][A-Za-z0-9]+)?|PC|PVA|HIPS|PP|PEEK|PEI)\b/i.test(
      `${profile.name} ${profile.inherits ?? ''}`,
    )
  ) {
    return 'filament'
  }

  // An untyped leaf with no machine/filament signature is the process preset
  // in OrcaSlicer's profile tree (layer height, walls, speeds, supports, ...).
  return 'process'
}

function profileValueAt(profile: ImportedProfileFile, key: string, index: number): string | undefined {
  const raw = profile.settings._passthrough?.[key]
  if (Array.isArray(raw)) return raw[index] ?? raw[0]
  if (raw !== undefined) return raw

  const topLevel: unknown =
    key === 'filament_type'
      ? profile.settings.filament_type
      : key === 'nozzle_temperature'
        ? profile.settings.nozzle_temperature
        : key === 'hot_plate_temp' || key === 'hot_plate_temp_initial_layer'
          ? profile.settings.bed_temperature
          : key === 'fan_min_speed'
            ? profile.settings.fan_min_speed
            : undefined
  if (topLevel === undefined || topLevel === null) return undefined
  return String(topLevel)
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/** Infer a known material from the profile name when OrcaSlicer omitted its base type. */
export function inferImportedFilamentType(profile: ImportedProfileFile): string | undefined {
  const declared = importedFilamentTypes(profile.settings)
  if (declared.length > 0) return declared[0]
  const haystack = `${profile.name} ${profile.inherits ?? ''}`
  for (const key of Object.keys(FILAMENT_PRESETS).sort((a, b) => b.length - a.length)) {
    const boundary = new RegExp(`(?:^|[^a-z0-9])${escapeRegExp(key)}(?:$|[^a-z0-9])`, 'i')
    if (boundary.test(haystack)) return key
  }
  return profile.name.trim() || undefined
}

/** Recover a useful model name from a machine leaf profile and its parent. */
export function inferImportedPrinterModel(profile: ImportedProfileFile): string | undefined {
  const declared = profile.settings.printer_model
  if (typeof declared === 'string' && declared.trim()) return declared
  const inherited = profile.inherits?.trim()
  if (inherited) {
    const model = inherited.replace(/\s+\d+(?:\.\d+)?\s+nozzle$/i, '').trim()
    if (model) return model
  }
  return profile.name.trim() || undefined
}

interface ImportedFilamentSlot {
  type: string
  passthrough: Record<string, string>
}

function importedFilamentSlots(profile: ImportedProfileFile): ImportedFilamentSlot[] {
  const declared = importedFilamentTypes(profile.settings)
  const count = Math.max(1, declared.length)
  return Array.from({ length: count }, (_, index) => {
    const type = declared[index] ?? inferImportedFilamentType(profile) ?? profile.name
    const passthrough: Record<string, string> = {}
    const keys = new Set(Object.keys(profile.settings._passthrough ?? {}))
    keys.add('filament_type')
    keys.add('nozzle_temperature')
    keys.add('hot_plate_temp')
    keys.add('hot_plate_temp_initial_layer')
    keys.add('fan_min_speed')
    keys.add('filament_settings_id')

    for (const key of keys) {
      const value = profileValueAt(profile, key, index)
      if (value !== undefined) passthrough[key] = value
    }
    // A missing filament_type is common in a leaf profile that inherits a
    // system material (e.g. "Voron PETG" -> Generic PETG @System). The name
    // inference above makes the slot explicit for the engine and the UI.
    passthrough.filament_type = type
    // Keep the leaf profile's name available to the panel even when the
    // source omitted filament_settings_id; it is useful confirmation that the
    // custom temperature/flow values came from the selected file.
    passthrough.filament_settings_id ??= profile.name
    return { type, passthrough }
  })
}

function numericValue(value: string | undefined): number | undefined {
  if (value === undefined) return undefined
  const n = Number(value)
  return Number.isFinite(n) ? n : undefined
}

// A user OrcaSlicer filament leaf is a delta from its `inherits` chain, not a
// fully resolved preset. When two such leaves are merged, a key can therefore
// be present for PETG and absent for PLA. Filling that hole with the first
// value from another slot is unsafe: it turns a missing PLA flow ratio into
// PETG's flow ratio, or copies a material-specific fan/PA setting to a nozzle
// that uses a different material. These are the engine defaults from the
// pinned PrintConfig.cpp. Material-dependent values are handled below from
// the selected material preset where this app has one.
const IMPORTED_FILAMENT_ENGINE_DEFAULTS: Record<string, string> = {
  filament_diameter: '1.75',
  filament_flow_ratio: '1',
  filament_max_volumetric_speed: '2',
  filament_density: '0',
  filament_cost: '0',
  filament_flush_temp: '0',
  filament_flush_volumetric_speed: '0',
  enable_pressure_advance: '0',
  pressure_advance: '0.02',
  reduce_fan_stop_start_freq: '0',
  filament_adaptive_volumetric_speed: '0',
  filament_cooling_before_tower: '10',
  filament_ironing_flow: 'nil',
  filament_ironing_spacing: 'nil',
  filament_ironing_inset: 'nil',
  filament_ironing_speed: 'nil',
  activate_air_filtration: '0',
  activate_air_filtration_during_print: '1',
  activate_air_filtration_on_completion: '1',
  during_print_exhaust_fan_speed: '60',
  complete_print_exhaust_fan_speed: '80',
}

/**
 * The value for a missing entry in one imported filament leaf. Returning
 * `undefined` for an unknown option is intentional: a partial vector for an
 * option whose type/default this app does not know cannot be completed safely,
 * so the merge drops that option instead of assigning another material's
 * value to it. The engine will then use its own default for every slot.
 */
function importedFilamentFallback(key: string, type: string, slotIndex: number): string | undefined {
  const preset = FILAMENT_PRESETS[type]
  switch (key) {
    case 'filament_colour':
      return slotColour(slotIndex)
    case 'fan_min_speed':
      return String(preset?.fan_min_speed ?? 20)
    case 'nozzle_temperature':
    case 'nozzle_temperature_initial_layer':
      return String(preset?.nozzle_temperature ?? DISPLAY_DEFAULTS.nozzle_temperature)
    case 'hot_plate_temp':
    case 'hot_plate_temp_initial_layer':
      return String(preset?.bed_temperature ?? DISPLAY_DEFAULTS.bed_temperature)
    case 'filament_start_gcode':
    case 'filament_end_gcode':
      return ''
    default:
      return IMPORTED_FILAMENT_ENGINE_DEFAULTS[key]
  }
}

function passthroughValues(config: OrcaConfig, key: string): string[] {
  const raw = config._passthrough?.[key]
  if (raw === undefined) return []
  return Array.isArray(raw) ? raw : [raw]
}

/**
 * The headless engine still runs OrcaSlicer's extruder-variant normalization.
 * Desktop PresetBundle fills these two internal vectors while loading a
 * profile; a raw JSON import bypasses that loader, so without them the engine
 * falls back to variant index 0 for every filament. The visible `filament_map`
 * can then correctly select T1 while its temperature/flow vectors have already
 * collapsed to slot 0 — a particularly dangerous silent failure for PETG.
 */
function filamentEngineRouting(
  config: OrcaConfig,
  n: number,
  nozzles: number,
  filamentMap: string[],
): { variants: string[]; selfIndices: string[] } {
  const declaredVariants = passthroughValues(config, 'filament_extruder_variant')
  const declaredSelfIndices = passthroughValues(config, 'filament_self_index')
  const variantForNozzle = (nozzleIndex: number): string => {
    const explicit = passthroughValues(config, 'extruder_variant_list')[nozzleIndex]
    if (explicit?.trim())
      return (
        explicit
          .split(',')
          .map((value) => value.trim())
          .find(Boolean) ?? DEFAULT_FILAMENT_EXTRUDER_VARIANT
      )
    return DEFAULT_FILAMENT_EXTRUDER_VARIANT
  }

  const variants = Array.from({ length: n }, (_, filamentIndex) => {
    // A desktop bundle may contain more than one variant entry per filament;
    // when its self-index is present, use the first entry belonging to this
    // filament. Otherwise the ordinary one-entry-per-slot layout applies.
    const indexedEntry = declaredSelfIndices.findIndex((value) => Number(value) === filamentIndex + 1)
    const declared = declaredVariants[indexedEntry >= 0 ? indexedEntry : filamentIndex]
    if (declared?.trim()) return declared
    const mappedNozzle = Number(filamentMap[filamentIndex]) - 1
    return variantForNozzle(
      Number.isInteger(mappedNozzle) && mappedNozzle >= 0 && mappedNozzle < nozzles
        ? mappedNozzle
        : filamentIndex % nozzles,
    )
  })

  // This app models one variant per visible filament slot. That is sufficient
  // for the imported Voron files and prevents a stale multi-variant vector
  // from pointing an engine option past the N-long values we emit here.
  return { variants, selfIndices: Array.from({ length: n }, (_, index) => String(index + 1)) }
}

/**
 * Make independent filament files deterministic without hiding an explicit
 * order for custom materials. A folder selection does not promise that the
 * browser will preserve the order in which the OS returned its entries. For
 * the materials OrcaWeb knows, the same order as the material presets gives a
 * predictable mapping (PLA, PETG, ABS, TPU); unknown materials retain their
 * relative selection order after those entries.
 */
function orderImportedFiles(files: ImportedProfileFile[]): ImportedProfileFile[] {
  const categoryOrder: Record<ImportedProfileType, number> = { machine: 0, process: 1, print: 2, filament: 3 }
  const materialOrder = new Map(Object.keys(FILAMENT_PRESETS).map((name, index) => [name, index]))
  return files
    .map((file, index) => ({ file, index }))
    .sort((a, b) => {
      const categoryDifference = categoryOrder[a.file.type] - categoryOrder[b.file.type]
      if (categoryDifference !== 0) return categoryDifference
      if (a.file.type !== 'filament') return a.index - b.index
      const aMaterial = materialOrder.get(inferImportedFilamentType(a.file) ?? '') ?? Number.MAX_SAFE_INTEGER
      const bMaterial = materialOrder.get(inferImportedFilamentType(b.file) ?? '') ?? Number.MAX_SAFE_INTEGER
      return aMaterial - bMaterial || a.index - b.index
    })
    .map(({ file }) => file)
}

/**
 * Merge the separate files OrcaSlicer uses for a real profile selection.
 * Machine/process/print files form the normal config layers; every filament
 * file becomes one entry in the per-filament vectors. This is deliberately a
 * pure function so a multi-file import can be validated before it changes UI
 * state and the exact mapping can be covered without a browser.
 */
export function mergeImportedProfileFiles(files: ImportedProfileFile[]): ImportedProfileSet {
  if (files.length === 0) throw new Error('Select at least one OrcaSlicer profile JSON file.')

  for (const type of ['machine', 'process', 'print'] as const) {
    const count = files.filter((file) => file.type === type).length
    if (count > 1) throw new Error(`Select at most one ${type} profile.`)
  }

  const orderedFiles = orderImportedFiles(files)
  const nonFilament = orderedFiles
    .filter((file) => file.type !== 'filament')
    .map((file) => {
      if (file.type !== 'machine' || file.settings.printer_model !== undefined) return file.settings
      const printer_model = inferImportedPrinterModel(file)
      return printer_model ? { ...file.settings, printer_model } : file.settings
    })

  const filamentFiles = orderedFiles.filter((file) => file.type === 'filament')
  const filamentSlots = filamentFiles.flatMap(importedFilamentSlots)
  const merged = mergeConfigLayers(...nonFilament)

  if (filamentSlots.length > 0) {
    const first = filamentSlots[0]
    const firstPatch: Partial<OrcaConfig> = {
      filament_type: first.type,
      nozzle_temperature: numericValue(first.passthrough.nozzle_temperature),
      bed_temperature: numericValue(first.passthrough.hot_plate_temp),
      fan_min_speed: numericValue(first.passthrough.fan_min_speed),
    }
    for (const key of Object.keys(firstPatch)) {
      if (firstPatch[key as keyof OrcaConfig] === undefined) delete firstPatch[key as keyof OrcaConfig]
    }
    Object.assign(merged, mergeConfigLayers(merged, firstPatch))

    const keys = new Set(filamentSlots.flatMap((slot) => Object.keys(slot.passthrough)))
    const passthrough: PassthroughConfig = { ...(merged._passthrough ?? {}) }
    for (const key of keys) {
      const values = filamentSlots.map((slot) => slot.passthrough[key])
      const resolved = values.map(
        (value, index) => value ?? importedFilamentFallback(key, filamentSlots[index].type, index),
      )
      if (resolved.every((value): value is string => value !== undefined)) {
        passthrough[key] = resolved
      }
      // A partially present, unknown option is deliberately not forwarded.
      // Forwarding it as a short vector makes later filament ids read the
      // wrong entry; borrowing another material's entry is even worse. Known
      // options above get an engine/material default, while an omitted
      // unknown option is resolved by the engine for every slot.
    }
    merged._passthrough = passthrough
  }

  return {
    name: orderedFiles.length === 1 ? orderedFiles[0].name : orderedFiles.map((file) => file.name).join(' + '),
    sourceNames: orderedFiles.map((file) => file.name),
    profileTypes: orderedFiles.map((file) => file.type),
    settings: merged,
  }
}

/**
 * The per-filament options the engine needs in order to treat a config as
 * having N filaments rather than one.
 *
 * Every filament-indexed vector has to be N long, because the engine indexes
 * them by filament id; a short one is read out of bounds. The three that are
 * easy to miss:
 *
 *  - `filament_colour` defines the count (see SLOT_COLOURS).
 *  - `flush_volumes_matrix` holds one N×N sub-matrix *per nozzle*, laid out
 *    end to end — `get_flush_volumes_matrix()` slices it by nozzle id.
 *  - `flush_multiplier` has one entry per nozzle, and is what
 *    `GCode::append_full_config()` divides the matrix length by to check it
 *    ("Flush volumes matrix do not match to the correct size!").
 *
 * `filament_map` assigns each slot to a physical extruder (1-based). Slots are
 * spread round-robin over the available nozzles, so a single-nozzle AMS-style
 * printer maps every slot to extruder 1, while a dual-nozzle machine alternates
 * — which is what produces genuine T0/T1 tool changes.
 *
 * Everything here only *fills in* what the config does not already say. An
 * imported multi-material profile brings its own colours, diameters, per-slot
 * temperatures and flush matrix, and those are the user's values: `_passthrough`
 * is spread over the resolved config, so regenerating them from a stock preset
 * would silently replace what was imported. See `per()` for the priority order.
 */
export function withFilamentSlots(config: OrcaConfig, filaments: string[]): OrcaConfig {
  const ui = filaments.filter((name) => name in FILAMENT_PRESETS)
  // An imported profile can declare more filaments than the UI has slots for
  // (a multi-material project file). The queue's picker offers those slots
  // too — it reads the same count — so they need the same per-filament
  // vectors; sizing only the UI's slots is exactly what leaves the engine
  // indexing past the end of one.
  const n = Math.max(ui.length, declaredSlotCount(config))
  // One slot is the pre-existing single-filament config, untouched.
  if (n < 2) return config
  // Nozzle count is deliberately resolved from the *merged* config rather than
  // the built-in printer preset: an imported machine profile (a real
  // dual-nozzle H2D) only shows up once the layers are combined, and it is
  // what decides whether the slots land on one nozzle or alternate across two.
  const extra = multiFilamentPassthrough(config, ui, n, physicalNozzleCount(config))
  return { ...config, _passthrough: { ...config._passthrough, ...extra } }
}

/**
 * How many filaments the config already declares on its own, ignoring the UI's
 * slot list — `filament_colour` is the engine's count, and `filament_type` is
 * the multi-value form a multi-material profile arrives in.
 */
function declaredSlotCount(config: OrcaConfig): number {
  const pt = config._passthrough
  if (Array.isArray(pt?.filament_colour)) return pt.filament_colour.length
  return Array.isArray(pt?.filament_type) ? pt.filament_type.length : 1
}

/**
 * Where slot `i` takes its per-filament values from.
 *
 * Slot 0 is the slot the settings panel edits, so it reads the *resolved*
 * config — manual overrides and any imported filament layer included — not the
 * stock preset for its material. These arrays land in `_passthrough`, which
 * the worker spreads *over* the resolved config, so reading the preset here is
 * what used to make adding a second slot silently revert a hand-typed nozzle
 * or bed temperature back to the preset value.
 *
 * Slots the UI knows about take their stock preset. Slots beyond it exist only
 * because an imported profile declared them, so they take whatever it named.
 *
 * `filament_type` is the one field slot 0 cannot read straight off the resolved
 * config: ORCA_FIELD_MAP collapses a multi-value option to a single scalar for
 * display, so an imported multi-material profile leaves `config.filament_type`
 * as the joined "PLA,PETG" rather than this slot's own type. The unflattened
 * array is still in the passthrough, so take slot 0's entry from there.
 *
 * Reading the resolved config for slot 0 is only sound while the panel's
 * material *is* the one this slot is named after. The resolved config's
 * per-filament scalars (temperatures) describe `ui[0]`; if the import declared a
 * different type for slot 0 they would describe a different material than the
 * slot's own name — the #161 contradiction (slot announced PLA, extruded at
 * ABS's temperature). When they disagree, rebuild slot 0 from the *declared*
 * material's own preset instead, so its type and temperatures cannot describe
 * different filaments. A material this app ships no preset for still cannot be
 * given a real temperature, but it no longer inherits the panel material's.
 */
function slotSource(config: OrcaConfig, ui: string[], i: number): Partial<OrcaConfig> {
  const declared = config._passthrough?.filament_type
  const perSlot = Array.isArray(declared) ? declared : undefined
  if (i === 0) {
    const type = perSlot?.[0]
    if (!type) return config
    if (type === ui[0]) return { ...config, filament_type: type }
    return FILAMENT_PRESETS[type] ?? { filament_type: type }
  }
  if (i < ui.length) return FILAMENT_PRESETS[ui[i]] ?? {}
  const type = perSlot?.[i]
  if (!type) return {}
  return FILAMENT_PRESETS[type] ?? { filament_type: type }
}

/**
 * Options the settings panel edits, and therefore the ones whose slot 0 has to
 * come from the *resolved* config rather than from whatever the imported layer
 * declared — a manual override lives in the resolved config, and `_passthrough`
 * is spread over it, so preferring the declared value here would silently
 * revert the user's edit (the #159 interaction). Every other per-filament
 * option has no UI of its own, so a declared value is the best answer for any
 * slot including the first.
 *
 * "Edits" means whatever toEngineConfig() writes from a panel field, not just
 * the fields the panel names. Its one "Bed temp" knob fans out to *both*
 * hot_plate_temp and hot_plate_temp_initial_layer, so both belong here — with
 * only the first listed, a single-slot config put the typed value in both
 * while a multi-slot one silently left the first layer on the imported
 * profile's temperature. `nozzle_temperature_initial_layer` is deliberately
 * absent for exactly the same reason read the other way: toEngineConfig()
 * never writes it, so there is no panel value for a declared one to contradict.
 */
const PANEL_EDITED_SLOT_OPTIONS = new Set([
  'filament_type',
  'nozzle_temperature',
  'hot_plate_temp',
  'hot_plate_temp_initial_layer',
])

/**
 * Colour for a slot the config did not name one for. Past the hand-picked
 * palette (only reachable when an imported profile declares more slots than
 * the UI offers) walk the hue circle by the golden angle instead of repeating
 * it, so the extra slots stay visually distinct from each other.
 */
function slotColour(i: number): string {
  if (i < SLOT_COLOURS.length) return SLOT_COLOURS[i]
  const hue = ((i * 137.508) % 360) / 360
  // Standard HSL -> RGB (the hue2rgb helper), at a saturation and lightness
  // picked to sit alongside SLOT_COLOURS rather than for any property of their
  // own. Derived from those two rather than written out as literals: the ramp's
  // slope is a function of the min/max it moves between, and an earlier
  // revision had them disagree by a factor of two — leaving the piecewise curve
  // discontinuous at both joins, so some hues came out muddy while this comment
  // still claimed a plain HSL conversion.
  const saturation = 0.62
  const lightness = 0.55
  const chroma = (1 - Math.abs(2 * lightness - 1)) * saturation
  const min = lightness - chroma / 2
  const max = lightness + chroma / 2
  const slope = 6 * chroma
  const channel = (offset: number): string => {
    const t = (hue + offset) % 1
    const v = t < 1 / 6 ? min + slope * t : t < 1 / 2 ? max : t < 2 / 3 ? max - slope * (t - 1 / 2) : min
    return Math.round(v * 255)
      .toString(16)
      .padStart(2, '0')
  }
  return `#${channel(1 / 3)}${channel(0)}${channel(2 / 3)}`
}

/**
 * Whether this (multi-slot) config should slice with a prime tower. An explicit
 * choice wins over the default in priority order: the modeled top-level field
 * (the settings-panel toggle) first, then whatever an imported profile declared
 * in `_passthrough`, then PRIME_TOWER_DEFAULT_ENABLED. `_passthrough` normally
 * only carries this when a profile was imported *before* enable_prime_tower was
 * modeled — a fresh import routes it to the top-level field via ORCA_FIELD_MAP —
 * but reading both keeps either shape honoured.
 */
function primeTowerEnabled(config: OrcaConfig): boolean {
  if (config.enable_prime_tower !== undefined) return config.enable_prime_tower
  const declared = config._passthrough?.enable_prime_tower
  const raw = Array.isArray(declared) ? declared[0] : declared
  if (raw !== undefined) return raw === '1' || raw.toLowerCase() === 'true' || raw.toLowerCase() === 'yes'
  return PRIME_TOWER_DEFAULT_ENABLED
}

function multiFilamentPassthrough(config: OrcaConfig, ui: string[], n: number, nozzles: number): PassthroughConfig {
  const sources = Array.from({ length: n }, (_, i) => slotSource(config, ui, i))

  // Slot 0 is taken from the import rather than the panel when the import named
  // a material for it that the panel isn't showing (slotSource rebuilds it from
  // the declared material). In that state the resolved config describes a
  // *different* material than slot 0, so its PANEL_EDITED options must prefer
  // what the import declared for the slot over the resolved value — otherwise
  // the temperature is read off the panel's material while the type is the
  // import's. See slotSource() and #161.
  const declaredType0 = Array.isArray(config._passthrough?.filament_type)
    ? config._passthrough.filament_type[0]
    : undefined
  const declaredTypes = Array.isArray(config._passthrough?.filament_type)
    ? config._passthrough.filament_type
    : undefined
  // `!!` and not `!== undefined`: an empty declared type is "no type" to
  // slotSource (`if (!type) return config`), so it must stay the agree path here
  // too or the two disagree on a degenerate entry.
  const slot0FromImport = !!declaredType0 && declaredType0 !== ui[0]

  /** Whatever the config already carries for `key`, one entry per slot. */
  const declared = (key: string): (string | undefined)[] => {
    const raw = config._passthrough?.[key]
    if (raw === undefined) return []
    return Array.isArray(raw) ? raw : [raw]
  }

  /**
   * One value per slot for an option with no UI and nothing to derive it from:
   * whatever the config declared for that slot, else `fallback`. Used for the
   * options `per()` below cannot serve because they have no material to read.
   */
  const declaredOr = (key: string, fallback: (i: number) => string): string[] => {
    const values = declared(key)
    return Array.from({ length: n }, (_, i) => values[i] ?? fallback(i))
  }

  /**
   * One value per slot, preferring what the config already declared for that
   * slot over anything derived. An imported multi-material profile is the only
   * thing that can declare these, and its values are the user's — regenerating
   * them from a stock preset is the same silent-revert bug PANEL_EDITED_SLOT_
   * OPTIONS exists to avoid, one slot further down the list.
   *
   * A slot the UI names is the exception: the user picked that material in the
   * panel, so it outranks whatever an older import happened to say. For a later
   * slot with no scalar editor, an imported value remains authoritative while
   * the picker still names the same material; choosing another material is the
   * explicit rebuild request.
   *
   * That exception is only sound while `pick` genuinely reads the slot's own
   * material — it is what makes the derived value more current than the
   * declared one. An option with nothing to pick has no such value to offer
   * and would only overwrite the import with `fallback`, so it belongs in
   * `declaredOr()` above instead. `filament_diameter` sat here with `() => undefined`
   * and silently reset an imported 2.85 mm profile's second slot to 1.75.
   */
  const per = (key: string, pick: (src: Partial<OrcaConfig>) => unknown, fallback: string | number): string[] => {
    const own = declared(key)
    const derived = (i: number) => String(pick(sources[i]) ?? fallback)
    return Array.from({ length: n }, (_, i) => {
      if (i === 0) {
        // When slot 0 is the import's own material, prefer its declared value —
        // `derived(0)` reads slotSource's rebuilt slot (the declared material's
        // preset), which the import's own per-slot value still outranks.
        if (slot0FromImport) return own[0] ?? derived(0)
        return PANEL_EDITED_SLOT_OPTIONS.has(key) ? derived(0) : (own[0] ?? derived(0))
      }
      if (i < ui.length) {
        // Slot 0 has a visible scalar editor, but later slots only have a
        // material picker. Preserve a custom imported value for a later slot
        // when the picker is showing the same material; a different picker
        // value is an explicit request to rebuild that slot from its preset.
        // This is what lets a Voron PETG leaf (240 °C) remain 240 °C in slot 2
        // even though the app's stock PETG preset uses another temperature.
        const declaredType = declaredTypes?.[i]
        if (declaredType && declaredType === ui[i]) return own[i] ?? derived(i)
        return derived(i)
      }
      return own[i] ?? derived(i)
    })
  }

  // Per-filament G-code hooks. The engine reads these with .at(filament_id)
  // (GCode.cpp's filament_start_gcode lookup), so a vector left at its
  // one-entry default throws the moment anything prints with a filament other
  // than the first — which is why assigning an object to slot 2 used to fail
  // while slot 1 worked. Pad whatever the printer or imported profile already
  // set across the new slots rather than blanking it: overwriting with "" is a
  // silent way to drop a preset's own filament start G-code (a K-factor line,
  // say), which a single-slot config would still have honoured.
  const padHook = (key: 'filament_start_gcode' | 'filament_end_gcode'): string[] => {
    const raw = config._passthrough?.[key]
    const existing = raw === undefined ? [] : Array.isArray(raw) ? raw : [raw]
    return Array.from({ length: n }, (_, i) => existing[i] ?? existing[0] ?? '')
  }

  /**
   * A declared vector, but only when it is already exactly the shape this slot
   * count and nozzle count require. Unlike the per-slot options above these
   * cannot be honoured entry by entry: the engine validates their whole length
   * and rejects anything else outright ("Flush volumes matrix do not match to
   * the correct size!"), so one sized for the profile's own filament or nozzle
   * count has to be regenerated rather than padded.
   */
  const declaredIfSized = (key: string, length: number, ok: (v: string) => boolean = () => true) => {
    const own = declared(key)
    if (own.length !== length) return undefined
    return own.every((v) => v !== undefined && ok(v)) ? (own as string[]) : undefined
  }

  // One N×N matrix per nozzle: 0 to purge a filament into itself, FLUSH_VOLUME
  // between two different ones.
  const matrix: string[] = []
  for (let nozzle = 0; nozzle < nozzles; nozzle++)
    for (let from = 0; from < n; from++)
      for (let to = 0; to < n; to++) matrix.push(String(from === to ? 0 : FLUSH_VOLUME))

  // A profile that already assigns its slots to nozzles knows better than
  // round-robin — but only if it names nozzles this machine has. Anything else
  // (a map carried over from a printer with more extruders) would have the
  // engine index one that does not exist.
  const namesANozzle = (v: string) => Number.isInteger(Number(v)) && Number(v) >= 1 && Number(v) <= nozzles

  const filamentMap =
    declaredIfSized('filament_map', n, namesANozzle) ?? Array.from({ length: n }, (_, i) => String((i % nozzles) + 1))
  const engineRouting = filamentEngineRouting(config, n, nozzles, filamentMap)
  const primeTower = primeTowerEnabled(config)

  const base: PassthroughConfig = {
    filament_type: per('filament_type', (p) => p.filament_type, DISPLAY_DEFAULTS.filament_type),
    filament_colour: declaredOr('filament_colour', slotColour),
    // No FILAMENT_PRESETS entry carries a diameter, so there is nothing a UI
    // slot could derive — declared value first for every slot, 1.75 only where
    // nothing said otherwise. See per()'s doc for why this is not per().
    filament_diameter: declaredOr('filament_diameter', () => DEFAULT_FILAMENT_DIAMETER),
    nozzle_temperature: per('nozzle_temperature', (p) => p.nozzle_temperature, DISPLAY_DEFAULTS.nozzle_temperature),
    nozzle_temperature_initial_layer: per(
      'nozzle_temperature_initial_layer',
      (p) => p.nozzle_temperature,
      DISPLAY_DEFAULTS.nozzle_temperature,
    ),
    hot_plate_temp: per('hot_plate_temp', (p) => p.bed_temperature, DISPLAY_DEFAULTS.bed_temperature),
    hot_plate_temp_initial_layer: per(
      'hot_plate_temp_initial_layer',
      (p) => p.bed_temperature,
      DISPLAY_DEFAULTS.bed_temperature,
    ),
    filament_start_gcode: padHook('filament_start_gcode'),
    filament_end_gcode: padHook('filament_end_gcode'),
    filament_map: filamentMap,
    filament_map_mode: 'Manual',
    filament_extruder_variant: engineRouting.variants,
    filament_self_index: engineRouting.selfIndices,
    flush_volumes_matrix: declaredIfSized('flush_volumes_matrix', nozzles * n * n) ?? matrix,
    flush_multiplier: declaredIfSized('flush_multiplier', nozzles) ?? Array.from({ length: nozzles }, () => '1'),
    // The structure the flush volumes above flush *into*. Without it a
    // multi-material plate defines a purge with nowhere to deposit it — the
    // engine's own default for this is off (see primeTowerEnabled), so it has
    // to be turned on here rather than left to the engine. #163.
    // prime_tower_width and the other tower dimensions have working engine
    // defaults and reach the slice through toEngineConfig() / an import's own
    // _passthrough, so they need no default injected here.
    //
    // Placement (wipe_tower_x/y) is intentionally NOT set here. It depends on
    // the tower's footprint, which is driven by the *loaded model's height* —
    // data this pre-slice config layer does not have. OrcaSlicer's own
    // placement (PartPlateList::set_default_wipe_tower_pos_for_plate) lives in
    // the GUI and never runs headless, so the WASM bridge ports it instead
    // (clamp_wipe_tower_to_bed in orca-wasm/bridge/slicer.cpp): it anchors at
    // desktop's default position and clamps the tower onto the bed once the mesh
    // is loaded. That is the right place for it, not a mesh-blind heuristic here.
    enable_prime_tower: primeTower ? '1' : '0',
  }

  // A wipe tower is only valid under relative extruder addressing, and the
  // reset that addressing needs, or Print::validate() hard-fails the slice —
  // see withPrimeTowerAddressing()'s doc for the exact engine checks. Only
  // when the tower is actually on: a multi-material plate without one keeps the
  // absolute addressing the bridge defaults to, exactly as it sliced before.
  return primeTower ? { ...base, ...withPrimeTowerAddressing(config) } : base
}

/**
 * The two companion options a prime tower cannot slice without, both enforced
 * by Print::validate() in the engine (orca/src/libslic3r/Print.cpp):
 *
 *  - `use_relative_e_distances = 1`. The wipe tower is *only* supported under
 *    relative extruder addressing ("The Wipe Tower is currently only supported
 *    with the relative extruder addressing"). The WASM bridge otherwise forces
 *    this off, because relative addressing itself needs the reset below and the
 *    headless build ships no printer G-code to supply it (see slicer.cpp).
 *  - a per-layer `G92 E0`. On a Marlin-flavour, non-Bambu printer, relative
 *    addressing without an exact-uppercase "G92 E0" in the layer-change G-code
 *    fails validation ("Relative extruder addressing requires resetting the
 *    extruder position at each layer"). Bambu printers are exempt, but adding
 *    it is harmless there, so it goes in unconditionally rather than depending
 *    on which printer the config turns out to be.
 *
 * The reset is appended to whatever `before_layer_change_gcode` the config
 * already carries rather than replacing it — an imported printer profile's own
 * layer G-code (a real "G92 E0" line among it included) must survive. The
 * engine matches "^[ \t]*G92[ \t]*E0…$" per line, so a value already carrying
 * that line is left untouched and any other content keeps the reset on its own
 * appended line.
 */
function withPrimeTowerAddressing(config: OrcaConfig): PassthroughConfig {
  const raw = config._passthrough?.before_layer_change_gcode
  const existing = (Array.isArray(raw) ? raw[0] : raw) ?? ''
  const hasReset = /^[ \t]*G92[ \t]*E(0(\.0*)?|\.0+)[ \t]*(;.*)?$/m.test(existing)
  return {
    use_relative_e_distances: '1',
    before_layer_change_gcode: hasReset ? existing : existing ? `${existing}\nG92 E0` : 'G92 E0',
  }
}

/**
 * One label per real filament slot, in engine order — what the queue's
 * per-object picker lists and, via its length, the number of slots anything
 * assigned to a slot may legally name.
 *
 * Reads the same count the engine does (`filament_colour`, else the
 * multi-value `filament_type` an imported multi-material profile arrives in),
 * so it cannot disagree with what withFilamentSlots() actually sized —
 * declaredSlotCount() is the one place either of them asks.
 *
 * That includes the single-slot case, which is why it is *clamped* to one
 * label rather than handed straight to filamentSlots(). filamentSlots() splits
 * the scalar `filament_type` on [;,], and a profile can arrive carrying a
 * plain "PLA;PETG" there with no per-slot array behind it (a hand-written
 * profile, or an older persisted setting — real OrcaSlicer JSON uses arrays,
 * which land in `_passthrough` and are counted above). Passing that through
 * would offer a Slot 2 the engine has no filament for: withFilamentSlots()
 * reads the same declaredSlotCount(), returns early at `n < 2` and sizes
 * nothing, so the assignment's extruderId would index a one-filament config.
 * Display text is display text — see filamentSlots()'s doc and #155.
 */
export function filamentSlotLabels(config: OrcaConfig): string[] {
  const types = config._passthrough?.filament_type
  const perSlot = Array.isArray(types) ? types : undefined
  const count = declaredSlotCount(config)
  if (count < 2) return filamentSlots(config).slice(0, 1)
  const fallback = String(config.filament_type ?? DISPLAY_DEFAULTS.filament_type)
  return Array.from({ length: count }, (_, i) => perSlot?.[i] || fallback)
}

/** The subset of an imported profile the Material dropdown needs to label it. */
export interface ImportedFilamentSource {
  type: 'machine' | 'filament' | 'process' | 'print' | 'set'
  name: string
  settings: Partial<OrcaConfig>
}

/**
 * What the settings panel's Material dropdown shows for each slot whose material
 * came from an imported profile rather than a dropdown pick — the import's own
 * name, verbatim, so a profile naming a material this app ships no preset for
 * (e.g. "PETG-CF @Hotend") is displayed exactly rather than silently coerced or
 * left describing whatever was selected before the import. One entry per panel
 * slot; `undefined` for a slot means "show the normal preset dropdown", and a
 * whole `undefined` result means no slot has an imported label.
 *
 * A bare FILAMENT_PRESETS key is deliberately *not* labelled: findPresetKeyByField
 * already re-points such a slot to that preset (the dropdown shows it as a normal
 * editable entry), and adding it as a read-only option would only duplicate one
 * already in the list. Only a name the app can't represent as a preset is worth
 * surfacing verbatim. See #161.
 */
export function importedFilamentSlotLabels(
  imported: ImportedFilamentSource | null | undefined,
  selectedFilaments: string[],
): (string | undefined)[] | undefined {
  if (!imported || imported.type === 'machine' || imported.type === 'process') return undefined
  const pt = imported.settings._passthrough
  // Real multi-material profiles carry a descriptive per-slot id
  // (filament_settings_id) and a base type array; a single-filament profile
  // declares a scalar type and carries its display name at the top level.
  const ids = Array.isArray(pt?.filament_settings_id)
    ? pt.filament_settings_id
    : typeof pt?.filament_settings_id === 'string'
      ? [pt.filament_settings_id]
      : undefined
  const types = Array.isArray(pt?.filament_type) ? pt.filament_type : undefined
  const scalarType =
    typeof imported.settings.filament_type === 'string' && !imported.settings.filament_type.includes(',')
      ? imported.settings.filament_type
      : undefined
  if (!ids && !types && !scalarType) return undefined
  const presetKeys = Object.keys(FILAMENT_PRESETS)
  return selectedFilaments.map((slot, i) => {
    const label =
      ids?.[i] ??
      (i === 0 && imported.type === 'filament' ? imported.name : undefined) ??
      types?.[i] ??
      (i === 0 ? scalarType : undefined)
    if (label === undefined || label === slot || presetKeys.includes(label)) return undefined
    return label
  })
}

export function buildConfig(
  printer: string,
  filament: string | string[],
  preset: string,
  overrides: Partial<OrcaConfig> = {},
): OrcaConfig {
  // The first slot drives every scalar the settings panel shows; the rest only
  // exist as the per-filament arrays added below.
  const filaments = (Array.isArray(filament) ? filament : [filament]).filter((name) => name in FILAMENT_PRESETS)
  const slots = filaments.length > 0 ? filaments : ['PLA']
  // Unknown printer names (e.g. a stale selection saved by an older build) fall
  // back to the first bundled printer instead of crashing the config merge.
  const printerPreset = PRINTER_PRESETS[printer] ?? PRINTER_PRESETS[Object.keys(PRINTER_PRESETS)[0]] ?? {}
  const sources = [
    printerPreset,
    FILAMENT_PRESETS[slots[0]] ?? {},
    PRESETS.find((p) => p.name === preset)?.config ?? {},
    overrides,
  ]
  // A plain {...a, ...b} spread would let a later source's _passthrough
  // wholesale replace an earlier one's instead of merging them — e.g. the
  // quality preset's _passthrough (its own unmapped fields) would silently
  // discard the printer preset's machine_start_gcode/machine_end_gcode.
  // Merge _passthrough across all sources field-by-field instead.
  const merged: OrcaConfig = {}
  let passthrough: PassthroughConfig | undefined
  for (const source of sources) {
    const { _passthrough, ...rest } = source
    Object.assign(merged, rest)
    if (_passthrough) passthrough = { ...passthrough, ..._passthrough }
  }
  if (passthrough) merged._passthrough = passthrough
  return merged
}

/**
 * The four corners of a rectangular bed, in the "XxY" vertex format
 * OrcaSlicer's `printable_area` uses and parsePrintableArea() reads back.
 * Shared by toEngineConfig() (which joins them into the flat comma-separated
 * string the engine's set_deserialize_strict expects) and
 * exportOrcaProfileJson() (which writes the JSON array form real profiles
 * use), so the two can't disagree about the winding or the origin corner.
 */
function bedCorners(x: number, y: number): string[] {
  return ['0x0', `${x}x0`, `${x}x${y}`, `0x${y}`]
}

/**
 * Nozzle diameters OrcaSlicer ships machine presets for. printerPresetName()
 * below builds "<model> <diameter> nozzle" from the configured diameter, so a
 * diameter outside this set names a preset that does not exist.
 */
const STOCK_NOZZLE_DIAMETERS: readonly number[] = [0.2, 0.25, 0.4, 0.6, 0.8]

/**
 * The name of the desktop OrcaSlicer printer preset this config corresponds
 * to, following OrcaSlicer's own machine-preset naming convention
 * "<printer model> <nozzle diameter> nozzle" (e.g. "Bambu Lab P1S 0.4
 * nozzle" — verified against the profiles shipped inside OrcaSlicer 2.4.2).
 *
 * Needed because a process/filament preset OrcaSlicer will actually accept
 * must name the printers it applies to in `compatible_printers`: without it
 * the preset is rejected outright ("process not compatible with printer",
 * CLI exit -17), and an empty list does not mean "any printer". Verified by
 * slicing with the exported files against a stock OrcaSlicer install.
 *
 * A guess, necessarily — this app never sees the user's actual preset list,
 * and a vendor whose presets don't follow the convention won't match. That
 * only costs the user editing one field in a plain-text JSON, whereas
 * omitting the key makes the export unusable for everyone.
 */
function printerPresetName(config: OrcaConfig): string | undefined {
  if (config.printer_model === undefined || config.nozzle_diameter === undefined) return undefined
  return `${config.printer_model} ${config.nozzle_diameter} nozzle`
}

/**
 * Translate OrcaConfig field names to the literal OrcaSlicer config option
 * names the WASM bridge expects, for the fields where they differ.
 *
 * The bridge sends every key straight through to
 * `g_config.set_deserialize_strict(key, value)` (orca-wasm/bridge/slicer.cpp)
 * with no key translation of its own — an unrecognized key is silently
 * skipped. `default_speed` and `enable_ironing` are OrcaConfig-only names
 * with no matching real option (verified against PrintConfig.cpp), so
 * everywhere they were previously set — every PRESETS entry (Draft/Standard/
 * Fine) and any imported 3MF with ironing — silently had no effect on the
 * actual slice.
 *
 * Call this once, right before JSON.stringify'ing the config for orc_init.
 */
export function toEngineConfig(config: OrcaConfig): Record<string, unknown> {
  const { default_speed, enable_ironing, bed_temperature, ...rest } = config as OrcaConfig & Record<string, unknown>
  const out: Record<string, unknown> = { ...rest }
  if (config.bed_size_x !== undefined && config.bed_size_y !== undefined) {
    out.printable_area = bedCorners(config.bed_size_x, config.bed_size_y).join(',')
  }
  if (bed_temperature !== undefined) {
    // OrcaSlicer/BambuStudio's real option names — "bed_temperature" isn't
    // in its PrintConfig schema, so set_deserialize_strict silently dropped
    // it and every slice used the engine's own baked-in default instead of
    // the UI value (confirmed: exported .3mf always had hot_plate_temp=45
    // regardless of this field, for every printer preset).
    out.hot_plate_temp = bed_temperature
    out.hot_plate_temp_initial_layer = bed_temperature
  }
  if (default_speed !== undefined) {
    // "Speed of inner wall" (PrintConfig.cpp) — the closest real equivalent
    // to a general/default print speed; OrcaSlicer has no single knob that
    // also scales infill/support speeds, those remain independently set.
    out.inner_wall_speed = default_speed
  }
  if (enable_ironing !== undefined) {
    out.ironing_type = enable_ironing ? 'top' : 'no ironing'
  }
  return out
}

/**
 * Flatten an OrcaConfig into the single JSON object the WASM bridge consumes:
 * toEngineConfig's modeled output with the `_passthrough` block (raw engine
 * keys carried through unmodeled) merged over it, `_passthrough` winning on
 * conflicts — the same shape every slice/export call sends today.
 *
 * `hasFilamentSlot` is true when the slice carries a per-object filament
 * assignment, i.e. it goes through orc_slice_multi (which runs
 * clamp_wipe_tower_to_bed). When false the caller uses plain orc_slice, which
 * prints one object with the default filament and never clamps the tower — so
 * the prime tower is forced off, otherwise a still-multi-filament config would
 * build a tower at the raw, unclamped PrintConfig default, the exact off-bed
 * placement #163 fixes reached through a different call site. Multi-object and
 * 3MF-export paths pass true and keep whatever the profile declares.
 */
export function flattenSliceConfig(config: OrcaConfig, hasFilamentSlot: boolean): Record<string, unknown> {
  const { _passthrough, ...rest } = config
  const engineRest = toEngineConfig(rest)
  const flat: Record<string, unknown> = _passthrough ? { ...engineRest, ..._passthrough } : engineRest
  if (!hasFilamentSlot) flat.enable_prime_tower = '0'
  return flat
}

/**
 * Why an exported bundle won't load in desktop OrcaSlicer, or null when
 * nothing is known to be wrong with it. For the export button to say so
 * instead of reporting a plain success.
 *
 * Both cases end in the same place: everything hangs off the stock preset
 * name printerPresetName() derives. The process/filament files are matched
 * against the printer's `inherits` and nothing else, and the machine file has
 * to inherit from a printer OrcaSlicer already has — so if that name is
 * missing or names nothing, the bundle is rejected outright (exit -17).
 * Measured against OrcaSlicer 2.4.2: an export with neither key fails exactly
 * like one naming the wrong printer.
 *
 * Slicing in this app is unaffected either way — the engine takes any nozzle
 * diameter and needs no preset names — which is why this is a note attached
 * to the download rather than a blocked button or a restricted input.
 */
export function describeExportCompatibility(config: OrcaConfig): string | null {
  if (printerPresetName(config) === undefined) {
    return (
      'Exported — but this profile does not say which printer model and nozzle it is for, so ' +
      'OrcaSlicer cannot tell what the presets belong to and will reject them. Set "inherits" in ' +
      'machine.json (and "compatible_printers" in the other two) to a printer you have.'
    )
  }
  const nozzle = config.nozzle_diameter
  if (nozzle !== undefined && !STOCK_NOZZLE_DIAMETERS.includes(nozzle)) {
    return (
      `Exported — but OrcaSlicer ships no preset for a ${nozzle} mm nozzle, so it will reject ` +
      'machine.json until you point its "inherits" at a printer you have.'
    )
  }
  return null
}

// Which real OrcaSlicer profile file a field belongs to — desktop OrcaSlicer
// profiles are split into separate print/filament/printer presets, each only
// populated with its own option set (see exportOrcaProfileBundle below).
type FieldCategory = 'process' | 'filament' | 'machine'

// OrcaSlicer profile field → OrcaConfig key mapping.
// OrcaSlicer often encodes numbers as strings (e.g. "0.2") and percentages as
// "15%". 'ironing' is its own type (see enable_ironing/ironing_type below):
// unlike bool, its true/false <-> string mapping isn't "1"/"0", it's the
// IroningType enum (s_keys_map_IroningType in PrintConfig.cpp).
//
// `importOnly` marks a field name that must never be written back out by
// exportOrcaProfileJson(). Two kinds qualify, and both have already shipped
// as export bugs once:
//   - Aliases: an alternative real OrcaSlicer/PrusaSlicer spelling of a field
//     whose canonical name is another entry here (e.g. `perimeters` for
//     `wall_loops`). Accepted on import, but exporting the alias instead of
//     the canonical name is at best noise.
//   - Synthetic OrcaConfig-only names with no matching real PrintConfig
//     option at all (`default_speed`, `bed_temperature`, `bed_shape`). These
//     are the dangerous ones: desktop OrcaSlicer silently drops unrecognized
//     keys, so exporting one loses the user's setting with no error.
// Flagging them explicitly (rather than relying on declaration order, which
// is how `default_speed`/`enable_ironing`/`bed_temperature` each leaked into
// exports in the first place) makes REVERSE_FIELD_MAP below order-independent.
const ORCA_FIELD_MAP: Record<
  string,
  {
    key: keyof OrcaConfig
    type: 'num' | 'pct' | 'bool' | 'str' | 'ironing'
    category: FieldCategory
    importOnly?: true
  }
> = {
  layer_height: { key: 'layer_height', type: 'num', category: 'process' },
  // The real FFF field is initial_layer_print_height — initial_layer_height
  // (no "print_") is a distinct SLA-only option (PrintConfigDef::init_sla_params)
  // that set_deserialize_strict on our FFF-only build silently ignores. See
  // OrcaConfig.initial_layer_print_height's own doc comment.
  initial_layer_print_height: { key: 'initial_layer_print_height', type: 'num', category: 'process' },
  wall_loops: { key: 'wall_loops', type: 'num', category: 'process' },
  perimeters: { key: 'wall_loops', type: 'num', category: 'process', importOnly: true }, // alias
  wall_generator: { key: 'wall_generator', type: 'str', category: 'process' },
  top_shell_layers: { key: 'top_shell_layers', type: 'num', category: 'process' },
  bottom_shell_layers: { key: 'bottom_shell_layers', type: 'num', category: 'process' },
  sparse_infill_density: { key: 'sparse_infill_density', type: 'pct', category: 'process' },
  fill_density: { key: 'sparse_infill_density', type: 'pct', category: 'process', importOnly: true }, // alias
  sparse_infill_pattern: { key: 'sparse_infill_pattern', type: 'str', category: 'process' },
  fill_pattern: { key: 'sparse_infill_pattern', type: 'str', category: 'process', importOnly: true }, // alias
  outer_wall_speed: { key: 'outer_wall_speed', type: 'num', category: 'process' },
  external_perimeter_speed: { key: 'outer_wall_speed', type: 'num', category: 'process', importOnly: true }, // alias
  // inner_wall_speed is the real OrcaSlicer field; `default_speed` is an
  // OrcaConfig-only synthetic name (see toEngineConfig's doc comment) kept
  // readable on import so profiles this app exported before the fix still
  // load, but never written back out.
  inner_wall_speed: { key: 'default_speed', type: 'num', category: 'process' },
  default_speed: { key: 'default_speed', type: 'num', category: 'process', importOnly: true },
  travel_speed: { key: 'travel_speed', type: 'num', category: 'process' },
  initial_layer_speed: { key: 'initial_layer_speed', type: 'num', category: 'process' },
  first_layer_speed: { key: 'initial_layer_speed', type: 'num', category: 'process', importOnly: true }, // alias
  brim_width: { key: 'brim_width', type: 'num', category: 'process' },
  brim_type: { key: 'brim_type', type: 'str', category: 'process' },
  skirt_loops: { key: 'skirt_loops', type: 'num', category: 'process' },
  skirt_distance: { key: 'skirt_distance', type: 'num', category: 'process' },
  raft_layers: { key: 'raft_layers', type: 'num', category: 'process' },
  seam_position: { key: 'seam_position', type: 'str', category: 'process' },
  enable_support: { key: 'enable_support', type: 'bool', category: 'process' },
  support_type: { key: 'support_type', type: 'str', category: 'process' },
  // ironing_type is the real OrcaSlicer field (s_keys_map_IroningType: "no
  // ironing"/"top"/"topmost"/"solid") — there is no real "ironing" or
  // "enable_ironing" option (verified against PrintConfig.cpp). enable_ironing
  // is an OrcaConfig-only simplified boolean toggle for the UI; the 'ironing'
  // type below is what translates it to/from the real enum string, mirroring
  // toEngineConfig's own enable_ironing -> ironing_type conversion.
  ironing_type: { key: 'enable_ironing', type: 'ironing', category: 'process' },
  fuzzy_skin: { key: 'fuzzy_skin', type: 'str', category: 'process' },
  fuzzy_skin_thickness: { key: 'fuzzy_skin_thickness', type: 'num', category: 'process' },
  fuzzy_skin_point_dist: { key: 'fuzzy_skin_point_dist', type: 'num', category: 'process' },
  // Prime (wipe) tower — real OrcaSlicer process-preset options (#163). Mapped
  // so an imported profile's tower setting drives the panel toggle/width field
  // rather than landing in _passthrough unseen, and so both round-trip on export.
  enable_prime_tower: { key: 'enable_prime_tower', type: 'bool', category: 'process' },
  prime_tower_width: { key: 'prime_tower_width', type: 'num', category: 'process' },
  // filament fields
  filament_type: { key: 'filament_type', type: 'str', category: 'filament' },
  nozzle_temperature: { key: 'nozzle_temperature', type: 'num', category: 'filament' },
  temperature: { key: 'nozzle_temperature', type: 'num', category: 'filament', importOnly: true }, // alias
  // hot_plate_temp is the real OrcaSlicer field — "bed_temperature" is not in
  // its PrintConfig schema at all, so exporting it silently loses the user's
  // bed temperature on import into desktop OrcaSlicer (the same failure mode
  // toEngineConfig documents for the engine side).
  hot_plate_temp: { key: 'bed_temperature', type: 'num', category: 'filament' },
  bed_temperature: { key: 'bed_temperature', type: 'num', category: 'filament', importOnly: true },
  fan_min_speed: { key: 'fan_min_speed', type: 'num', category: 'filament' },
  // machine fields
  printer_model: { key: 'printer_model', type: 'str', category: 'machine' },
  nozzle_diameter: { key: 'nozzle_diameter', type: 'num', category: 'machine' },
  printable_height: { key: 'printable_height', type: 'num', category: 'machine' },
  max_print_height: { key: 'printable_height', type: 'num', category: 'machine', importOnly: true }, // alias
  // OrcaConfig-only: real OrcaSlicer machine profiles describe bed geometry
  // solely through printable_area (parseOrcaProfileJson derives circle-ness
  // from its vertex count), and "rectangle"/"circle" aren't valid values for
  // any polygon field — so this is never written back out.
  bed_shape: { key: 'bed_shape', type: 'str', category: 'machine', importOnly: true },
  // bed size — handled separately via parsePrintableArea() below
}

/**
 * Parse bed size from OrcaSlicer's `printable_area` field.
 *
 * OrcaSlicer stores bed corners as an array of "XxY" strings, e.g.:
 *   ["0x0", "256x0", "256x256", "0x256"]
 * or as a flat comma-joined string: "0x0,256x0,256x256,0x256"
 *
 * Returns { dims: [maxX, maxY], circle: boolean } or null if unparseable.
 * When the polygon has more than 8 points it's treated as a circular bed.
 */
function parsePrintableArea(raw: unknown): { dims: [number, number]; circle: boolean } | null {
  let pts: string[]
  if (Array.isArray(raw)) {
    pts = raw.map(String)
  } else {
    const s = String(raw).trim()
    if (!s) return null
    pts = s.split(',')
  }
  let minX = Infinity,
    maxX = -Infinity,
    minY = Infinity,
    maxY = -Infinity
  let pointCount = 0
  for (const pt of pts) {
    const parts = pt.trim().split('x')
    if (parts.length < 2) continue
    const x = parseFloat(parts[0]),
      y = parseFloat(parts[1])
    if (!Number.isNaN(x) && !Number.isNaN(y)) {
      minX = Math.min(minX, x)
      maxX = Math.max(maxX, x)
      minY = Math.min(minY, y)
      maxY = Math.max(maxY, y)
      pointCount++
    }
  }
  // Bed size is the bounding-box extent. For corner-origin rectangular beds the
  // origin is (0,0) so this equals maxX/maxY; for center-origin circular/delta
  // beds (coords −r..+r) this gives the full diameter, not the radius.
  const sizeX = maxX - minX,
    sizeY = maxY - minY
  if (!(sizeX > 0) || !(sizeY > 0)) return null
  // Circular beds are approximated as polygons with many vertices in OrcaSlicer profiles.
  return { dims: [sizeX, sizeY], circle: pointCount > 8 }
}

/**
 * Whether a lone value still means the same thing after being collapsed from
 * `["…"]` to a plain string on its way into `_passthrough`.
 *
 * For every option the engine joins with a plain separator the two forms are
 * interchangeable — a one-element join is the element. `coStrings` is the
 * exception, and it is not one this file can detect by key: the bridge routes
 * *arrays* through `escape_strings_cstyle()`, which quotes any element
 * containing ';' or opening with whitespace, while a *bare* string reaches
 * `ConfigOptionStrings::deserialize()` unquoted — and its
 * `unescape_strings_cstyle()` splits on ';' and strips leading whitespace. So
 * a `filament_start_gcode` of `["M900 K0.02 ; set K"]` survives as one value
 * when forwarded as an array and arrives chopped in two when collapsed.
 *
 * Knowing the option's type here is exactly what moving the join into the
 * bridge avoided (see json_array_to_config_string() and #140), so key off the
 * value instead: anything the quoting pass would have had to touch stays an
 * array and lets the bridge escape it. Keeping the array form is never *less*
 * correct — it only costs the tidier shape — and it is the shape the source
 * profile used anyway, so an import -> export round trip is unaffected.
 */
function collapsesCleanly(value: string): boolean {
  return !value.includes(';') && !/^["\s]/.test(value)
}

export function parseOrcaProfileJson(json: string): Partial<OrcaConfig> {
  try {
    const raw = JSON.parse(json) as Record<string, unknown>

    // Support array-wrapped values (OrcaSlicer wraps some fields: ["0.2"])
    function unwrap(v: unknown): unknown {
      return Array.isArray(v) && v.length === 1 ? v[0] : v
    }

    const config: Partial<OrcaConfig> = {}

    for (const [field, meta] of Object.entries(ORCA_FIELD_MAP)) {
      if (!(field in raw)) continue
      const raw_val = unwrap(raw[field])
      // meta.key's associated OrcaConfig property type varies per field (number/boolean/string)
      // depending on meta.type, which TS can't correlate — widen to unknown so writes below
      // type-check without an `any` escape hatch.
      const out = config as Record<keyof OrcaConfig, unknown>
      if (meta.type === 'num') {
        const n = parseFloat(String(raw_val))
        if (!Number.isNaN(n)) out[meta.key] = n
      } else if (meta.type === 'pct') {
        // "15%" → 15, "0.15" → 15, "15" → 15 (OrcaSlicer integer), "1" → 1 (not 100)
        const s = String(raw_val).trim()
        const parsed = parseFloat(s)
        const n = s.endsWith('%') ? parsed : parsed < 1 ? parsed * 100 : parsed
        if (!Number.isNaN(n)) out[meta.key] = Math.round(n)
      } else if (meta.type === 'bool') {
        const s = String(raw_val).toLowerCase()
        out[meta.key] = s === '1' || s === 'true' || s === 'yes'
      } else if (meta.type === 'ironing') {
        // s_keys_map_IroningType: "no ironing"/"top"/"topmost"/"solid" — any
        // non-empty value other than "no ironing" means ironing is enabled.
        const s = String(raw_val).trim().toLowerCase()
        out[meta.key] = s !== '' && s !== 'no ironing'
      } else {
        out[meta.key] = String(raw_val)
      }
    }

    // ── Bed size ─────────────────────────────────────────────────────────────
    // OrcaSlicer machine profiles carry printable_area / bed_size for bed dims.
    if ('printable_area' in raw) {
      const result = parsePrintableArea(raw.printable_area)
      if (result) {
        config.bed_size_x = result.dims[0]
        config.bed_size_y = result.dims[1]
        if (result.circle && !config.bed_shape) config.bed_shape = 'circle'
      }
    } else if ('bed_size' in raw) {
      // Some older profiles use bed_size: ["256", "256"] or "256x256"
      const bs = unwrap(raw.bed_size)
      if (Array.isArray(bs) && bs.length >= 2) {
        const x = parseFloat(String(bs[0])),
          y = parseFloat(String(bs[1]))
        if (!Number.isNaN(x) && x > 0) config.bed_size_x = x
        if (!Number.isNaN(y) && y > 0) config.bed_size_y = y
      } else {
        const result = parsePrintableArea(bs)
        if (result) {
          config.bed_size_x = result.dims[0]
          config.bed_size_y = result.dims[1]
          if (result.circle && !config.bed_shape) config.bed_shape = 'circle'
        }
      }
    }

    // ── Passthrough for unmapped OrcaSlicer fields ───────────────────────────
    // Collect every field not already processed so it can be forwarded verbatim
    // to the WASM slicer (which accepts any DynamicPrintConfig key) — except
    // including genuinely multi-extruder machine profiles: the crash that used
    // to make those unsafe was our own serialization fusing their multi-value
    // options into one entry, not the engine — see the array handling below
    // and issue #140.
    {
      const SKIP_META = new Set([
        'type',
        'name',
        'inherits',
        'from',
        'version',
        'description',
        '__proto__',
        'constructor',
        'prototype',
      ])
      // Keep printable_area verbatim so non-rectangular and offset beds survive
      // import -> export. toEngineConfig supplies a rectangular fallback for
      // built-in presets, while this passthrough value takes precedence later.
      const SKIP_BED = new Set(['bed_size'])
      const alreadyMapped = new Set(Object.keys(ORCA_FIELD_MAP))
      const passthrough: PassthroughConfig = Object.create(null) as PassthroughConfig
      for (const [field, val] of Object.entries(raw)) {
        if (SKIP_META.has(field) || SKIP_BED.has(field)) continue
        if (val === null || val === undefined) continue
        // Mapped fields normally stay out of the passthrough — they already
        // reached the engine through their OrcaConfig key. Multi-value ones are
        // the exception: ORCA_FIELD_MAP collapses an array to a single scalar
        // for the UI (nozzle_diameter ["0.4","0.4"] -> 0.4), which would tell
        // the engine a dual-nozzle machine has one nozzle. Forward those as
        // arrays too so the engine sees the real per-extruder values; the
        // scalar keeps driving the UI. See #140.
        const isMultiValue = Array.isArray(val) && val.length > 1
        if (alreadyMapped.has(field) && !isMultiValue) continue
        if (Array.isArray(val)) {
          // OrcaSlicer wraps values in arrays (single-extruder: ["0.8"], multi: ["0.8","1.0"]).
          // Forward the array *as an array* and let the WASM bridge join it: the
          // separator is a property of the option's type (';' for coStrings,
          // '#' between coPointsGroups groups, ',' for the rest), and only the
          // engine's own option registry knows which is which. Joining here with
          // a single guessed separator silently fused every multi-value string
          // and points-group option into one entry — see #140 and
          // json_array_to_config_string() in orca-wasm/bridge/slicer.cpp.
          const items = val
            .filter((x) => x !== null && x !== undefined)
            .map((x) => (typeof x === 'boolean' ? (x ? '1' : '0') : String(x)))
          // A single-entry array collapses to a plain string when that is
          // lossless (collapsesCleanly), keeping the old shape for every
          // ordinary single-extruder field rather than churning it. An empty
          // one is dropped rather than stored as "", also as before: real leaf
          // profiles carry [""] for every option they inherit rather than
          // override, and buildConfig() merges _passthrough field by field
          // with later layers winning — so a stored "" blanks out the built-in
          // preset's value for that key instead of leaving it alone. A
          // *multi*-entry array keeps its empties: there the length is load-
          // bearing (filament_start_gcode: ["", ""] is what sizes the vector).
          if (items.length === 1) {
            if (items[0] !== '') passthrough[field] = collapsesCleanly(items[0]) ? items[0] : items
          } else if (items.length > 1) passthrough[field] = items
          continue
        }
        const sv = typeof val === 'boolean' ? (val ? '1' : '0') : String(val)
        if (sv !== '') passthrough[field] = sv
      }
      if (Object.keys(passthrough).length > 0) config._passthrough = passthrough
    }

    return config
  } catch {
    return {}
  }
}

// Reverse of ORCA_FIELD_MAP: for each internal OrcaConfig key, the real
// OrcaSlicer field name to write on export. Built by skipping every
// `importOnly` entry rather than by taking the first field seen for a key —
// declaration order is not a safe signal here, and relying on it is exactly
// how default_speed, enable_ironing and bed_temperature each shipped as the
// exported name for a field OrcaSlicer doesn't have. A key whose only entry
// is importOnly (e.g. bed_shape) is deliberately absent, and so never
// exported at all.
const REVERSE_FIELD_MAP: Partial<Record<keyof OrcaConfig, string>> = {}
for (const [field, meta] of Object.entries(ORCA_FIELD_MAP)) {
  if (meta.importOnly) continue
  if (meta.key in REVERSE_FIELD_MAP) {
    throw new Error(
      `ORCA_FIELD_MAP: "${field}" and "${REVERSE_FIELD_MAP[meta.key]}" both claim to be the exported name for ` +
        `"${meta.key}" — exactly one entry per key may omit importOnly.`,
    )
  }
  REVERSE_FIELD_MAP[meta.key] = field
}

/**
 * `_passthrough` fields that must never reach an exported file, however they
 * were spelled in the profile they came from.
 *
 * Both of these name (or test for) the printer the *imported* profile was
 * written for, which is not necessarily the printer being exported here — a
 * process preset imported from a Creality profile carries
 * `compatible_printers: ["Creality Ender-3 0.4 nozzle"]`, and passing it
 * through means the exported bundle claims compatibility with a printer its
 * own machine.json isn't. OrcaSlicer then rejects the whole combination
 * ("process not compatible with printer", CLI exit -17) — the exact failure
 * the derived `compatible_printers` below exists to prevent. Dropping them
 * lets the derived value stand.
 */
const PASSTHROUGH_EXPORT_DENYLIST = new Set(['compatible_printers', 'compatible_printers_condition'])

/**
 * Passthrough options that are per-*machine*, not per-filament, so they belong
 * only in `machine.json`. Two kinds live here:
 *   - multi-material routing/purge options (`filament_map`,
 *     `flush_volumes_matrix`, …) that describe how the printer moves between
 *     slots, not any one filament;
 *   - `nozzle_diameter`, which on a multi-nozzle printer is a per-*nozzle*
 *     vector (an H2D carries two) round-robin-mapped to slots by nozzleCount(),
 *     NOT a per-slot vector. Without this exclusion filamentSlotConfig() would
 *     slice that array by slot index into each `filament-N.json` — reading a
 *     nozzle-indexed value as if it were filament-indexed, and putting a
 *     machine-only key on a filament preset besides.
 *
 * `withFilamentSlots()` writes all of these into `_passthrough` alongside the
 * per-slot filament vectors, and the passthrough dump would otherwise copy them
 * into every category file. A single-material filament preset carrying a whole
 * `flush_volumes_matrix` or a `nozzle_diameter` is meaningless (and out of
 * category), so they are skipped for every category except `machine`, where the
 * full, un-sliced value is written from the complete config.
 */
const MACHINE_MULTI_MATERIAL_OPTIONS = new Set([
  'filament_map',
  'filament_map_mode',
  'flush_volumes_matrix',
  'flush_multiplier',
  'nozzle_diameter',
])

/**
 * Serialize the current in-app config back into a single OrcaSlicer-
 * compatible profile JSON of one type (`process`/`filament`/`machine`) — the
 * mirror of parseOrcaProfileJson(). Only fields belonging to `category` are
 * written (canonical OrcaSlicer field names via REVERSE_FIELD_MAP), matching
 * how real OrcaSlicer print/filament/printer presets are three genuinely
 * separate option sets, not one flat file — a "process" preset with e.g.
 * nozzle_diameter (a machine-only option) mixed in isn't a shape desktop
 * OrcaSlicer's preset bundles ever produce themselves. Percentages are
 * written as "NN%" and printable_area as bed-corner strings, so each file is
 * also loadable by desktop OrcaSlicer as a user preset of that type.
 *
 * `_passthrough` fields can't be reliably attributed to a single category —
 * they arrive pre-merged from potentially multiple sources (buildConfig
 * merges every preset layer's _passthrough together; parseOrcaProfileJson
 * dumps every unmapped field from whichever single file was imported into
 * one bag) — so they're written to every category's file rather than
 * risking silently dropping one. A passthrough field that doesn't belong to
 * a given file's category is simply an unrecognized key there, same as any
 * other key set_deserialize_strict doesn't know.
 *
 * A field this config leaves unset is deliberately absent from the output
 * rather than filled in from DISPLAY_DEFAULTS: unset means "whatever the
 * engine defaults to", and desktop OrcaSlicer resolves an absent key from
 * that same default, so omitting it is what keeps the exported preset
 * slicing the way this app sliced. That only holds while DISPLAY_DEFAULTS
 * agrees with the engine — see its own comment.
 *
 * Exported by exportOrcaProfileBundle() below for actual use; kept as its
 * own function (rather than inlined) so tests can assert one category's
 * output directly.
 */
export function exportOrcaProfileJson(config: OrcaConfig, name: string, category: FieldCategory): string {
  const { _passthrough, bed_size_x, bed_size_y, ...rest } = config
  const out: Record<string, unknown> = {
    type: category,
    name,
    from: 'User',
  }
  for (const [orcaKey, value] of Object.entries(rest)) {
    if (value === undefined || value === null) continue
    const field = REVERSE_FIELD_MAP[orcaKey as keyof OrcaConfig]
    if (!field) continue
    const meta = ORCA_FIELD_MAP[field]
    if (meta.category !== category) continue
    out[field] =
      meta.type === 'pct'
        ? `${value}%`
        : meta.type === 'ironing'
          ? value
            ? 'top'
            : 'no ironing'
          : typeof value === 'boolean'
            ? value
              ? '1'
              : '0'
            : String(value)
  }
  if (category === 'filament' && config.bed_temperature !== undefined) {
    // OrcaSlicer splits bed temperature into the steady-state and first-layer
    // options; the UI has one knob, so both get it — mirroring exactly what
    // toEngineConfig() sends to the engine, so an exported profile slices the
    // same way in desktop OrcaSlicer as it did here.
    out.hot_plate_temp_initial_layer = String(config.bed_temperature)
  }

  // Passthrough goes on *before* the derived keys below, not after. A
  // passthrough value describes the profile it was imported from; the derived
  // keys describe the selection actually being exported, so where the two
  // collide the derived one has to win. (Applying it last is how an imported
  // profile's foreign `compatible_printers` used to silently replace the
  // derived one and make the bundle unloadable.) printable_area is the one
  // deliberate exception, re-applied further down.
  if (_passthrough) {
    for (const [field, value] of Object.entries(_passthrough)) {
      if (PASSTHROUGH_EXPORT_DENYLIST.has(field)) continue
      if (category !== 'machine' && MACHINE_MULTI_MATERIAL_OPTIONS.has(field)) continue
      out[field] = value
    }
  }

  const printer = printerPresetName(config)
  if (printer && (category === 'process' || category === 'filament')) {
    // Exactly one entry, and it has to be the *stock* preset name, because
    // that is the only string this list is ever compared against.
    //
    // Measured against OrcaSlicer 2.4.2's CLI (the path this bundle is for):
    // the gate is OrcaSlicer.cpp's own `process_compatible` loop, not
    // Preset.cpp's is_compatible_with_printer(), and it tests each entry
    // against `new_printer_system_name` — the printer preset's `inherits`
    // value, never the preset's own name. Adding the exported machine file's
    // name here is therefore inert: verified, a list containing only that
    // name is rejected (exit -17) even though that file *is* the printer
    // being loaded. Its `inherits` (set below) is what makes the match.
    //
    // An absent or empty list is not "compatible with anything" either — the
    // loop simply never matches. Verified: dropping the key fails the same
    // -17. (Preset.cpp's separate GUI-side check does treat an empty list as
    // compatible-with-all, which is what makes this easy to get wrong.)
    out.compatible_printers = [printer]
  }
  if (printer && category === 'machine') {
    // A machine preset has to derive from a printer OrcaSlicer already knows;
    // a standalone one is rejected the same way an uncompatible process is.
    // Inheriting from the stock preset of the same model makes this a normal
    // user printer preset — verified end to end: the exported file slices,
    // and printer_model/nozzle_diameter/printable_height come from here.
    out.inherits = printer
  }
  if (category === 'machine') {
    // An imported profile's own printable_area wins over the rectangle
    // derived from bed_size_x/y, so non-rectangular and offset beds survive
    // import -> export (see parseOrcaProfileJson's SKIP_BED comment). Real
    // machine profiles use the array form, which the passthrough now preserves
    // as-is; the string branch still handles a value that reached us already
    // flattened (a hand-written profile, or an older persisted setting).
    const imported = _passthrough?.printable_area
    if (imported !== undefined) {
      out.printable_area = Array.isArray(imported)
        ? imported
        : imported
            .split(',')
            .map((vertex) => vertex.trim())
            .filter(Boolean)
    } else if (bed_size_x !== undefined && bed_size_y !== undefined) {
      out.printable_area = bedCorners(bed_size_x, bed_size_y)
    }
  }
  return JSON.stringify(out, null, 2)
}

/**
 * Collapse a multi-slot config down to the single filament in slot `i` — the
 * shape one filament preset file has to have.
 *
 * `withFilamentSlots()` stores every per-filament option in `_passthrough` as
 * an N-long vector (`filament_type: ["PLA","PETG"]`, `nozzle_temperature:
 * ["220","255"]`, …). A filament *preset* is single-material, so slot `i`'s
 * file wants each of those flattened to its own entry. We index every array in
 * the passthrough to `[i]`, not a curated subset: an imported multi-material
 * profile carries per-slot vectors this app never names (flow ratio, max
 * volumetric speed, …), and every one that actually reaches a filament file is
 * per-filament — leaving any as a full array would make each of the N files
 * read that vector's *first* entry (OrcaSlicer takes element 0 of an over-long
 * filament vector), so slots 2..N would silently inherit slot 0's value. A
 * shorter vector (a G-code hook padded to one entry, say) falls back to element
 * 0, which is that hook for all slots.
 *
 * The machine-only passthrough options are indexed here too but never reach a
 * filament file (exportOrcaProfileJson skips MACHINE_MULTI_MATERIAL_OPTIONS
 * outside `machine`), so the slice is inert for them. That exclusion is what
 * keeps a per-*nozzle* vector like `nozzle_diameter` — which is NOT per-slot —
 * from being mis-sliced into each preset; `machine.json` gets the full array
 * from the complete config instead.
 */
function filamentSlotConfig(config: OrcaConfig, i: number): OrcaConfig {
  const pt = config._passthrough
  if (!pt) return config
  const slot: PassthroughConfig = {}
  for (const [key, value] of Object.entries(pt)) {
    slot[key] = Array.isArray(value) ? (value[i] ?? value[0]) : value
  }
  return { ...config, _passthrough: slot }
}

/**
 * Export the current settings as a full OrcaSlicer preset bundle — one file
 * per real preset type (process/filament/machine), matching how desktop
 * OrcaSlicer itself stores and imports presets (see exportOrcaProfileJson's
 * own doc comment for why a single flat file can't represent this). Used by
 * SettingsPanel's "Export" button, which zips the files together so the whole
 * bundle downloads as one action.
 *
 * A multi-slot config emits one filament file *per slot* — `filament-1.json` …
 * `filament-N.json`, each a normal single-material preset built from that
 * slot's entries in the `_passthrough` vectors (see filamentSlotConfig).
 * OrcaSlicer counts materials by the number of separate filament preset files
 * (`--load-filaments "filament-1.json;filament-2.json"`), not by array length
 * inside one file: a single `filament.json` whose `filament_type` is an array
 * resolves back to a *single* filament, so a config sliced here as N materials
 * would not round-trip through the bundle (#162). A single-slot config keeps
 * emitting exactly one `filament.json`, unchanged.
 */
export function exportOrcaProfileBundle(
  config: OrcaConfig,
  baseName: string,
): { filename: string; category: FieldCategory; json: string }[] {
  const slots = declaredSlotCount(config)
  const filamentFiles =
    slots < 2
      ? [
          {
            filename: 'filament.json',
            category: 'filament' as const,
            json: exportOrcaProfileJson(config, `${baseName} (filament)`, 'filament'),
          },
        ]
      : Array.from({ length: slots }, (_, i) => ({
          filename: `filament-${i + 1}.json`,
          category: 'filament' as const,
          json: exportOrcaProfileJson(filamentSlotConfig(config, i), `${baseName} (filament ${i + 1})`, 'filament'),
        }))
  return [
    {
      filename: 'process.json',
      category: 'process' as const,
      json: exportOrcaProfileJson(config, `${baseName} (process)`, 'process'),
    },
    ...filamentFiles,
    {
      filename: 'machine.json',
      category: 'machine' as const,
      json: exportOrcaProfileJson(config, `${baseName} (machine)`, 'machine'),
    },
  ]
}
