#!/usr/bin/env bash
# Generated by scripts/gen-wsl-build-script.mjs from .github/workflows/build-wasm.yml —
# re-run that generator after editing the workflow rather than hand-editing this file.
set -e
# Which build-matrix leg to build locally — the workflow builds st and mt as
# two separate CI jobs (strategy.matrix.variant); this script builds one at a
# time. Override with WASM_VARIANT=mt.
export VARIANT="${WASM_VARIANT:-st}"
if [[ "$VARIANT" != "st" && "$VARIANT" != "mt" ]]; then
  echo "[build-local-wsl] WASM_VARIANT must be 'st' or 'mt', got: $VARIANT" >&2
  exit 1
fi
export ORCA_VERSION="${ORCA_VERSION:-v2.4.2}"
export OCCT_VERSION="${OCCT_VERSION:-7.8.1}"
export EMSDK_VERSION="${EMSDK_VERSION:-3.1.74}"
export ONETBB_VERSION="${ONETBB_VERSION:-v2021.13.2}"
export EMSDK="${EMSDK:-/opt/emsdk}"
if [[ "$VARIANT" == "mt" ]]; then
  export OUTPUT_NAME="slicer-mt"
else
  export OUTPUT_NAME="slicer"
fi
if [[ "$VARIANT" == "mt" ]]; then
  export BOOST_THREADING="multi"
else
  export BOOST_THREADING="single"
fi
if [[ "$VARIANT" == "mt" ]]; then
  export SLIC3R_WASM_MT="ON"
else
  export SLIC3R_WASM_MT="OFF"
fi
if [[ "$VARIANT" == "mt" ]]; then
  export EXTRA_CXX_FLAGS="-pthread"
else
  export EXTRA_CXX_FLAGS=""
fi
source "$EMSDK/emsdk_env.sh"
export CCACHE_DIR="$HOME/.cache/ccache"
mkdir -p "$CCACHE_DIR"
ccache --max-size=2G >/dev/null 2>&1 || true
# Local-only: rolling-release distros (Arch, etc.) ship a much newer CMake
# than CI's ubuntu-latest. Several deps (EXPAT 2.5.0 confirmed) declare an
# old cmake_minimum_required() that newer CMake rejects outright ("Compatibility
# with CMake < 3.5 has been removed"). This env var is CMake's own documented
# escape hatch (3.31+) and applies to every invocation without patching each
# dep's CMakeLists.txt. Not needed in CI, so not added to build-wasm.yml.
export CMAKE_POLICY_VERSION_MINIMUM=3.5
cd "$(dirname "$0")/../.."   # repo root (this script lives in orca-wasm/scripts/)
echo "[build-local-wsl] repo root: $(pwd)"
echo "[build-local-wsl] ORCA_VERSION=$ORCA_VERSION VARIANT=$VARIANT"

# ══════════════════════════════════════════════════════════
# Checkout OrcaSlicer ${ORCA_VERSION}
# ══════════════════════════════════════════════════════════
(
if [ -d orca-wasm/orca/.git ]; then
  echo "[checkout] orca-wasm/orca already present — skip"
else
  rm -rf orca-wasm/orca
  git clone --depth 1 --branch "$ORCA_VERSION" \
    https://github.com/SoftFever/OrcaSlicer.git \
    orca-wasm/orca
fi
)

# ══════════════════════════════════════════════════════════
# Patch OrcaSlicer source
# ══════════════════════════════════════════════════════════
(
python3 orca-wasm/patches/apply.py
)

# ══════════════════════════════════════════════════════════
# Build WASM deps — Boost
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
BOOST_VERSION="1.83.0"
BOOST_UNDERSCORE="${BOOST_VERSION//./_}"
INSTALL="$(pwd)/orca-wasm/deps-install"
# _v2 suffix: manually bumped, not tied to BOOST_VERSION — the
# BOOST_LOG_NO_THREADS fix above changed Boost's build *flags*,
# not its pinned version, so BOOST_VERSION alone wouldn't
# invalidate a stale cached build. Restore-keys below prefix-match
# regardless of this suffix (see "Restore dep cache"'s own
# comment on why a version bump alone isn't sufficient), so
# without this the mt job would restore its OLD, wrongly-built
# libboost_log.a from cache and skip rebuilding it entirely.
STAMP="${INSTALL}/.boost_built_${VARIANT}_v2"
mkdir -p "${INSTALL}"
[[ -f "${STAMP}" ]] && echo "[boost] stamp exists — skip" && exit 0

echo "[boost] downloading Boost ${BOOST_VERSION}…"
mkdir -p /tmp/boost
curl -fL --retry 3 \
  "https://archives.boost.org/release/${BOOST_VERSION}/source/boost_${BOOST_UNDERSCORE}.tar.gz" \
  | tar xz -C /tmp/boost
cd "/tmp/boost/boost_${BOOST_UNDERSCORE}"

echo "[boost] bootstrapping b2…"
./bootstrap.sh --with-toolset=clang

echo "[boost] writing user-config.jam for emscripten toolset…"
printf "using clang : emscripten : em++ :\n<archiver>emar\n<ranlib>emranlib ;\n" > ~/user-config.jam

echo "[boost] building with b2 (emscripten, static, threading=${BOOST_THREADING})…"
B2_DEFINES=(
  "define=BOOST_LOG_WITHOUT_SYSLOG=1"
  # Always on — see the step comment above for why this must match
  # libslic3r's own (unconditional, upstream) compile flags rather
  # than varying by matrix.variant.
  "define=BOOST_LOG_NO_THREADS=1"
)
if [[ "${VARIANT}" == "mt" ]]; then
  B2_EXTRA_CXXFLAGS="cxxflags=-pthread"
else
  # Existing st behavior, unchanged.
  B2_DEFINES+=(
    "define=BOOST_THREAD_DONT_USE_PTHREAD=1"
  )
  B2_EXTRA_CXXFLAGS=""
fi

./b2 \
  toolset=clang-emscripten \
  variant=release \
  link=static \
  threading="${BOOST_THREADING}" \
  --layout=system \
  --prefix="${INSTALL}" \
  --with-atomic \
  --with-chrono \
  --with-date_time \
  --with-filesystem \
  --with-iostreams \
  --with-locale \
  --with-log \
  --with-nowide \
  --with-program_options \
  --with-regex \
  --with-system \
  --with-thread \
  "${B2_DEFINES[@]}" \
  ${B2_EXTRA_CXXFLAGS} \
  -j"$(nproc)" \
  install

echo "[boost] installed headers:"
ls "${INSTALL}/include/boost/version.hpp" && echo "  boost/version.hpp OK"
echo "[boost] installed libs (sample):"
ls "${INSTALL}/lib/libboost_system"* 2>/dev/null | head -3 || echo "  no libboost_system found!"
touch "${STAMP}"

)

# ══════════════════════════════════════════════════════════
# Build WASM deps — GMP / MPFR / CGAL
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
INSTALL="$(pwd)/orca-wasm/deps-install"
STAMP="${INSTALL}/.math_built_${VARIANT}"
[[ -f "${STAMP}" ]] && echo "[math] stamp exists — skip" && exit 0

GMP_VERSION=6.3.0
MPFR_VERSION=4.2.1
CGAL_VERSION=5.6.2
DL=/tmp/math-dl
mkdir -p "${DL}"

# ── GMP ──────────────────────────────────────────────────────
echo "[gmp] building GMP ${GMP_VERSION}…"
# Use GNU FTP mirror (gmplib.org blocks GitHub Actions runners)
curl -fL --retry 3 \
  "https://ftp.gnu.org/gnu/gmp/gmp-${GMP_VERSION}.tar.xz" | tar xJ -C "${DL}"
cd "${DL}/gmp-${GMP_VERSION}"
# CONFIG_SITE seeds cache vars before any check runs; export provides
# the same value via direct env inheritance for all sub-configures.
printf 'gmp_cv_asm_label_suffix=":"\n' > /tmp/gmp_site.sh
export gmp_cv_asm_label_suffix=":"
export CFLAGS="${EXTRA_CXX_FLAGS}"
export CXXFLAGS="${EXTRA_CXX_FLAGS}"
CONFIG_SITE=/tmp/gmp_site.sh emconfigure ./configure \
  --prefix="${INSTALL}" \
  --host=wasm32-unknown-emscripten \
  --disable-shared --enable-static --disable-assembly \
  --enable-cxx
emmake make -j"$(nproc)"
make install

# ── MPFR ─────────────────────────────────────────────────────
echo "[mpfr] building MPFR ${MPFR_VERSION}…"
curl -fL --retry 3 \
  "https://ftp.gnu.org/gnu/mpfr/mpfr-${MPFR_VERSION}.tar.xz" | tar xJ -C "${DL}"
cd "${DL}/mpfr-${MPFR_VERSION}"
emconfigure ./configure \
  --prefix="${INSTALL}" --with-gmp="${INSTALL}" --disable-shared --enable-static
emmake make -j"$(nproc)"
make install
unset CFLAGS CXXFLAGS

# ── CGAL (header-only + cmake config) ────────────────────────
echo "[cgal] installing CGAL ${CGAL_VERSION} cmake config…"
curl -fL --retry 3 \
  "https://github.com/CGAL/cgal/releases/download/v${CGAL_VERSION}/CGAL-${CGAL_VERSION}.tar.xz" \
  | tar xJ -C "${DL}"
cd "${DL}/CGAL-${CGAL_VERSION}"
# CGAL is header-only; cmake just installs headers + CMake config files.
# Use plain cmake (no emcmake) for the install step.
cmake -S . -B /tmp/cgal-build -G Ninja \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DGMP_INCLUDE_DIR="${INSTALL}/include" \
  -DGMP_LIBRARIES="${INSTALL}/lib/libgmp.a" \
  -DMPFR_INCLUDE_DIR="${INSTALL}/include" \
  -DMPFR_LIBRARIES="${INSTALL}/lib/libmpfr.a"
cmake --build /tmp/cgal-build --target install

touch "${STAMP}"

)

# ══════════════════════════════════════════════════════════
# Build WASM deps — Eigen3 / nlohmann / EXPAT / NLopt
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
INSTALL="$(pwd)/orca-wasm/deps-install"
# Stamp name is version-suffixed (like the OCCT step below) AND
# variant-suffixed (new — EXPAT/NLopt's compiled objects now
# differ by -pthread) so that bumping either invalidates it even
# if the cache step above only fell back to an older cache via
# restore-keys.
STAMP="${INSTALL}/.headers_built_eigen5.0.1_nlohmann3.11.3_expat2.5.0_nlopt2.7.1_cereal1.3.2_${VARIANT}"
[[ -f "${STAMP}" ]] && echo "[headers+expat+nlopt] cached" && exit 0

# ── Eigen3 (header-only, install cmake config) ────────────────
echo "[eigen3] installing…"
curl -fL "https://gitlab.com/libeigen/eigen/-/archive/5.0.1/eigen-5.0.1.tar.gz" \
  | tar xz -C /tmp/
cmake -S /tmp/eigen-5.0.1 -B /tmp/eigen-build -G Ninja \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DBUILD_TESTING=OFF
cmake --build /tmp/eigen-build --target install

# ── nlohmann/json (header-only, install cmake config) ─────────
echo "[nlohmann] installing…"
git clone --depth 1 --branch v3.11.3 \
  https://github.com/nlohmann/json.git /tmp/nlohmann
cmake -S /tmp/nlohmann -B /tmp/nlohmann-build -G Ninja \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DJSON_BuildTests=OFF \
  -DJSON_Install=ON
cmake --build /tmp/nlohmann-build --target install

# ── EXPAT (XML parser — needed by libslic3r) ──────────────────
echo "[expat] building…"
curl -fL "https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.xz" \
  | tar xJ -C /tmp/
emcmake cmake -S /tmp/expat-2.5.0 -B /tmp/expat-build -G Ninja \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DEXPAT_BUILD_TOOLS=OFF \
  -DEXPAT_BUILD_EXAMPLES=OFF \
  -DEXPAT_BUILD_TESTS=OFF \
  -DEXPAT_SHARED_LIBS=OFF \
  "-DCMAKE_C_FLAGS=${EXTRA_CXX_FLAGS}"
emmake cmake --build /tmp/expat-build --target install

# ── NLopt (optimizer — needed by libslic3r) ───────────────────
echo "[nlopt] building…"
curl -fL "https://github.com/stevengj/nlopt/archive/v2.7.1.tar.gz" \
  | tar xz -C /tmp/
emcmake cmake -S /tmp/nlopt-2.7.1 -B /tmp/nlopt-build -G Ninja \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DNLOPT_CXX=ON \
  -DNLOPT_PYTHON=OFF \
  -DNLOPT_GUILE=OFF \
  -DNLOPT_MATLAB=OFF \
  -DNLOPT_OCTAVE=OFF \
  -DNLOPT_SWIG=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  "-DCMAKE_C_FLAGS=${EXTRA_CXX_FLAGS}" \
  "-DCMAKE_CXX_FLAGS=${EXTRA_CXX_FLAGS}"
emmake cmake --build /tmp/nlopt-build --target install

# ── cereal (header-only serialization — needed by libslic3r) ─────
echo "[cereal] installing…"
git clone --depth 1 --branch v1.3.2 \
  https://github.com/USCiLab/cereal.git /tmp/cereal
cmake -S /tmp/cereal -B /tmp/cereal-build -G Ninja \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DJUST_INSTALL_CEREAL=ON \
  -DSKIP_PERFORMANCE_COMPARISON=ON \
  -DBUILD_SANDBOX=OFF \
  -DBUILD_DOC=OFF
cmake --build /tmp/cereal-build --target install

touch "${STAMP}"

)

# ══════════════════════════════════════════════════════════
# Build WASM deps — libnoise
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
INSTALL="$(pwd)/orca-wasm/deps-install"
STAMP="${INSTALL}/.libnoise_built_${VARIANT}"
[[ -f "${STAMP}" ]] && echo "[libnoise] stamp exists — skip" && exit 0

echo "[libnoise] downloading Orca-deps-libnoise 1.0…"
curl -fL --retry 3 \
  "https://github.com/SoftFever/Orca-deps-libnoise/archive/refs/tags/1.0.tar.gz" \
  | tar xz -C /tmp/
mv /tmp/Orca-deps-libnoise-1.0 /tmp/libnoise-src

echo "[libnoise] configuring with Emscripten…"
emcmake cmake -S /tmp/libnoise-src -B /tmp/libnoise-build -G Ninja \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DCMAKE_BUILD_TYPE=Release \
  "-DCMAKE_CXX_FLAGS=${EXTRA_CXX_FLAGS}"

echo "[libnoise] building…"
emmake cmake --build /tmp/libnoise-build --target install -j"$(nproc)"

echo "[libnoise] verifying install…"
ls "${INSTALL}/include/libnoise/noise.h" && echo "  headers OK"
ls "${INSTALL}/lib/liblibnoise_static.a" && echo "  lib OK"
touch "${STAMP}"

)

# ══════════════════════════════════════════════════════════
# Build WASM deps — OCCT
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
OCCT_VERSION="7.8.1"
OCCT_TAG="V${OCCT_VERSION//./_}"
INSTALL="$(pwd)/orca-wasm/deps-install"
# _v2 suffix: manually bumped, not tied to OCCT_TAG — the -pthread
# fix below changed OCCT's build *flags* for mt, not its pinned
# version, so OCCT_TAG alone wouldn't invalidate a stale cached
# (non-pthread) build already sitting in the mt deps-install
# cache from before this fix (same gotcha as the Boost stamp
# bump above — the cache key itself doesn't encode these flags).
STAMP="${INSTALL}/.occt_built_${OCCT_TAG}_v2"
[[ -f "${STAMP}" ]] && echo "[occt] stamp exists — skip" && exit 0

echo "[occt] downloading OCCT ${OCCT_VERSION}…"
mkdir -p /tmp/occt/occt-src
curl -fL --retry 3 \
  "https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/${OCCT_TAG}.tar.gz" \
  | tar xz -C /tmp/occt/occt-src --strip-components=1

echo "[occt] excluding ExpToCasExe host tool…"
# ExpToCasExe is a developer-only code generator (regenerates STEP
# EXPRESS schema sources, which OCCT already ships pre-generated).
# Under Emscripten its versioned executable output (ExpToCasExe.js-7.8.1)
# breaks OCCT's install rule, which looks for "ExpToCasExe.wasm".
# We don't need it, so drop it from BUILD_TOOLKITS before configure.
python3 - <<'PYEOF'
import pathlib
p = pathlib.Path('/tmp/occt/occt-src/CMakeLists.txt')
t = p.read_text()
anchor = 'set (BUILD_TOOLKITS ${RAW_BUILD_TOOLKITS})'
assert anchor in t, 'OCCT BUILD_TOOLKITS anchor not found — OCCT layout changed'
p.write_text(t.replace(anchor, anchor + '\nlist (REMOVE_ITEM BUILD_TOOLKITS ExpToCasExe)', 1))
print('[occt-patch] excluded ExpToCasExe from BUILD_TOOLKITS')
PYEOF

echo "[occt] configuring with Emscripten…"
# OCCT ignores the standard BUILD_SHARED_LIBS flag — it selects the
# library type from its own BUILD_LIBRARY_TYPE cache variable, which
# defaults to "Shared" and then force-sets BUILD_SHARED_LIBS=ON
# (CMakeLists.txt:55, with no platform guard).  Emscripten cannot
# resolve transitive .so dependencies from outside its sysroot, so the
# link of OCCT's ExpToCasExe host tool fails with
# "libTKExpress.so: dependency not found: libTKernel.so".
# Setting BUILD_LIBRARY_TYPE=Static makes OCCT emit .a archives, which
# is the only flag that actually controls this.  The toolchain file is
# used directly (not emcmake) for explicit CMAKE_SYSTEM_NAME=Emscripten,
# and CMAKE_CROSSCOMPILING_EMULATOR=node lets cmake run any in-build
# codegen tools via Node.
#
# mt needs -pthread here too — this is a wholly separate cmake
# invocation from "Configure WASM build" below (its own toolchain
# file, not emcmake), so it never inherited that step's
# EXTRA_CXX_FLAGS. Missing this is exactly what caused a real link
# failure: OCCT's own -fexceptions runtime glue ("exceptions.o")
# got compiled without atomics/bulk-memory support and then linked
# into the final --shared-memory binary, even though the
# variant-suffixed Emscripten cache (a different, already-fixed
# bug) ruled out a stale-cache explanation — confirmed via
# "Install Emscripten" actually running (not cache-hit-skipped) on
# the run that still failed this way.
cmake \
  -S /tmp/occt/occt-src \
  -B /tmp/occt/build \
  -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE="${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DBUILD_LIBRARY_TYPE=Static \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_CROSSCOMPILING_EMULATOR="node" \
  -DBUILD_MODULE_Draw=OFF \
  -DBUILD_MODULE_Visualization=OFF \
  -DBUILD_MODULE_FoundationClasses=ON \
  -DBUILD_MODULE_ModelingData=ON \
  -DBUILD_MODULE_ModelingAlgorithms=ON \
  -DBUILD_MODULE_DataExchange=ON \
  -DBUILD_MODULE_ApplicationFramework=ON \
  -DUSE_FREETYPE=OFF \
  -DUSE_OPENGL2=OFF \
  -DUSE_TCL=OFF \
  -DUSE_TK=OFF \
  -DUSE_FFMPEG=OFF \
  -DUSE_FREEIMAGE=OFF \
  -DUSE_RAPIDJSON=OFF \
  -DUSE_DRACO=OFF \
  -DUSE_VTK=OFF \
  -DUSE_TBB=OFF \
  "-DCMAKE_CXX_FLAGS=-O2 -fexceptions -Wno-deprecated-anon-enum-enum-conversion -Wno-unknown-warning-option ${EXTRA_CXX_FLAGS}" \
  "-DCMAKE_C_FLAGS=-O2 ${EXTRA_CXX_FLAGS}"

echo "[occt] building (first run ~30–60 min)…"
cmake --build /tmp/occt/build -j"$(nproc)"

echo "[occt] installing to ${INSTALL}…"
cmake --install /tmp/occt/build

echo "[occt] verifying install…"
ls "${INSTALL}/lib/cmake/opencascade/OpenCASCADEConfig.cmake" \
  && echo "  cmake config OK"
ls "${INSTALL}/lib/libTKernel.a" && echo "  TKernel.a OK"
touch "${STAMP}"

)

# ══════════════════════════════════════════════════════════
# Patch Emscripten zlib/libjpeg ports for pthread (mt)
# ══════════════════════════════════════════════════════════
if [[ "$VARIANT" == "mt" ]]; then
(
source "$EMSDK/emsdk_env.sh"
python3 - <<'PYEOF'
import os
import pathlib

# Read EMSDK from the environment rather than interpolating it into
# this heredoc — the heredoc delimiter is quoted ('PYEOF') so bash
# performs no variable substitution inside it at all.
emsdk = os.environ["EMSDK"]
zlib_py = pathlib.Path(emsdk, "upstream/emscripten/tools/ports/zlib.py")
t = zlib_py.read_text()
# The "Cache Emscripten" step above caches the whole $EMSDK tree,
# including this file's own patched state from a previous run —
# so a cache hit restores an already-patched zlib.py, and this
# script must tolerate re-running against it instead of asserting.
if "variants = {'zlib-mt'" in t:
  print("[zlib-patch] already patched (cached emsdk) — skipping")
else:
  anchor = (
      "def needed(settings):\n"
      "  return settings.USE_ZLIB\n"
      "\n\n"
      "def get(ports, settings, shared):"
  )
  assert anchor in t, "zlib.py layout changed — pthread patch anchor not found"
  t = t.replace(anchor, (
      "variants = {'zlib-mt': {'PTHREADS': 1}}\n\n\n"
      "def needed(settings):\n"
      "  return settings.USE_ZLIB\n"
      "\n\n"
      "def get_lib_name(settings):\n"
      "  return 'libz-mt.a' if settings.PTHREADS else 'libz.a'\n"
      "\n\n"
      "def get(ports, settings, shared):"
  ), 1)
  anchor2 = (
      "    flags = ['-Wno-deprecated-non-prototype']\n"
      "    ports.build_port(source_path, final, 'zlib', srcs=srcs, flags=flags)\n"
      "\n"
      "  return [shared.cache.get_lib('libz.a', create, what='port')]"
  )
  assert anchor2 in t, "zlib.py build block changed — pthread patch anchor not found"
  t = t.replace(anchor2, (
      "    flags = ['-Wno-deprecated-non-prototype']\n"
      "    if settings.PTHREADS:\n"
      "      flags += ['-pthread']\n"
      "    ports.build_port(source_path, final, 'zlib', srcs=srcs, flags=flags)\n"
      "\n"
      "  return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]"
  ), 1)
  zlib_py.write_text(t)
  print("[zlib-patch] added pthread-aware zlib-mt variant")

libjpeg_py = pathlib.Path(emsdk, "upstream/emscripten/tools/ports/libjpeg.py")
t = libjpeg_py.read_text()
if "variants = {'libjpeg-mt'" in t:
  print("[libjpeg-patch] already patched (cached emsdk) — skipping")
else:
  anchor = (
      "def needed(settings):\n"
      "  return settings.USE_LIBJPEG\n"
      "\n\n"
      "def get(ports, settings, shared):"
  )
  assert anchor in t, "libjpeg.py layout changed — pthread patch anchor not found"
  t = t.replace(anchor, (
      "variants = {'libjpeg-mt': {'PTHREADS': 1}}\n\n\n"
      "def needed(settings):\n"
      "  return settings.USE_LIBJPEG\n"
      "\n\n"
      "def get_lib_name(settings):\n"
      "  return 'libjpeg-mt.a' if settings.PTHREADS else 'libjpeg.a'\n"
      "\n\n"
      "def get(ports, settings, shared):"
  ), 1)
  anchor2 = (
      "    ports.build_port(source_path, final, 'libjpeg', exclude_files=excludes)\n"
      "\n"
      "  return [shared.cache.get_lib('libjpeg.a', create, what='port')]"
  )
  assert anchor2 in t, "libjpeg.py build block changed — pthread patch anchor not found"
  t = t.replace(anchor2, (
      "    flags = []\n"
      "    if settings.PTHREADS:\n"
      "      flags += ['-pthread']\n"
      "    ports.build_port(source_path, final, 'libjpeg', exclude_files=excludes, flags=flags)\n"
      "\n"
      "  return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]"
  ), 1)
  libjpeg_py.write_text(t)
  print("[libjpeg-patch] added pthread-aware libjpeg-mt variant")
PYEOF

)
else
  echo "[skip] Patch Emscripten zlib/libjpeg ports for pthread (mt) — requires matrix.variant == 'mt', VARIANT=$VARIANT"
fi

# ══════════════════════════════════════════════════════════
# Build WASM deps — emscripten ports (zlib/png/jpeg)
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
SYSROOT_LIB="$EMSDK/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten"
if [[ "${VARIANT}" == "mt" ]]; then
  echo "[emports] building zlib-mt, libpng-mt, libjpeg-mt via embuilder…"
  embuilder build zlib-mt libpng-mt libjpeg-mt
  cp "${SYSROOT_LIB}/libz-mt.a" "${SYSROOT_LIB}/libz.a"
  cp "${SYSROOT_LIB}/libpng-mt.a" "${SYSROOT_LIB}/libpng.a"
  cp "${SYSROOT_LIB}/libjpeg-mt.a" "${SYSROOT_LIB}/libjpeg.a"
else
  echo "[emports] building zlib, libpng, libjpeg via embuilder…"
  embuilder build zlib libpng libjpeg
fi
echo "[emports] sysroot libs:"
ls "${SYSROOT_LIB}/libz.a" && echo "  libz OK"
ls "${SYSROOT_LIB}/libpng.a" && echo "  libpng OK"
ls "${SYSROOT_LIB}/libjpeg.a" && echo "  libjpeg OK"

)

# ══════════════════════════════════════════════════════════
# Build official oneTBB for WASM (mt)
# ══════════════════════════════════════════════════════════
if [[ "$VARIANT" == "mt" ]]; then
(
source "$EMSDK/emsdk_env.sh"
INSTALL="$(pwd)/orca-wasm/deps-install"
STAMP="${INSTALL}/.onetbb_${ONETBB_VERSION}"
[[ -f "${STAMP}" ]] && echo "[oneTBB] cached" && exit 0

git clone --depth 1 --branch "${ONETBB_VERSION}" \
  https://github.com/uxlfoundation/oneTBB.git /tmp/onetbb
emcmake cmake -S /tmp/onetbb -B /tmp/onetbb-build -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${INSTALL}" \
  -DBUILD_SHARED_LIBS=OFF \
  -DTBB_TEST=OFF \
  -DTBB_EXAMPLES=OFF \
  -DTBB_STRICT=OFF \
  -DTBB_DISABLE_HWLOC_AUTOMATIC_SEARCH=ON
cmake --build /tmp/onetbb-build --target install -j"$(nproc)"
test -f "${INSTALL}/lib/libtbb.a"
test -f "${INSTALL}/lib/cmake/TBB/TBBConfig.cmake"
touch "${STAMP}"

)
else
  echo "[skip] Build official oneTBB for WASM (mt) — requires matrix.variant == 'mt', VARIANT=$VARIANT"
fi

# ══════════════════════════════════════════════════════════
# Configure WASM build
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
WORK="$(pwd)"
DEP_INSTALL="${WORK}/orca-wasm/deps-install"
mkdir -p orca-wasm/build-wasm

# mt adds -pthread at compile time for the whole tree (libslic3r,
# bridge, and the final slicer target all need pthread-consistent
# object code — see ADR-011) and switches the TBB
# include dir (real oneTBB headers instead of the ST shims) +
# SLIC3R_WASM_MT compile define (see orca-wasm/bridge/CMakeLists.txt)
# so the one threading-aware bridge line flips.
COMMON_SHIM_DIR="${WORK}/orca-wasm/wasm/shims-common"
TBB_INCLUDE_DIR="${WORK}/orca-wasm/wasm/shims"
if [[ "${VARIANT}" == "mt" ]]; then
  TBB_INCLUDE_DIR="${DEP_INSTALL}/include"
fi

emcmake cmake \
  -S orca-wasm/orca \
  -B orca-wasm/build-wasm \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_PREFIX_PATH="${DEP_INSTALL}" \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  -DCMAKE_MODULE_PATH="${WORK}/orca-wasm/cmake" \
  -DCMAKE_PROJECT_INCLUDE_BEFORE="${WORK}/orca-wasm/cmake/wasm_find_paths.cmake" \
  -DSLIC3R_WASM=ON \
  -DSLIC3R_WASM_MT=${SLIC3R_WASM_MT} \
  -DSLIC3R_GUI=OFF \
  -DSLIC3R_STATIC=ON \
  -DSLIC3R_OPENCASCADE=ON \
  -DOCCT_WASM_DIR="${DEP_INSTALL}" \
  -DSLIC3R_OPENGL_IMGUI=OFF \
  -DTBB_SHIM_DIR="${TBB_INCLUDE_DIR}" \
  -DORCA_WEB_BRIDGE_DIR="${WORK}/orca-wasm/bridge" \
  -DORCA_WEB_WASM_DIR="${WORK}/orca-wasm/wasm" \
  -DORCA_WEB_SHIM_DIR="${TBB_INCLUDE_DIR}" \
  -DORCA_WEB_OVERRIDES_DIR="${WORK}/orca-wasm/overrides" \
  -DORCA_WEB_WASM_OUTPUT_NAME="${OUTPUT_NAME}" \
  -DBoost_NO_SYSTEM_PATHS=ON \
  -DBoost_NO_BOOST_CMAKE=ON \
  -DBOOST_ROOT="${DEP_INSTALL}" \
  -DBoost_ROOT="${DEP_INSTALL}" \
  -DCGAL_DIR="${DEP_INSTALL}/lib/cmake/CGAL" \
  -DNLOPT_LIBRARY="${DEP_INSTALL}/lib/libnlopt.a" \
  -DNLOPT_INCLUDE_DIR="${DEP_INSTALL}/include" \
  "-DCMAKE_CXX_FLAGS=-I${COMMON_SHIM_DIR} -I${TBB_INCLUDE_DIR} -fexceptions -DBOOST_HAS_PTHREADS=1 -DSLIC3R_WASM=1 -DSLIC3R_NO_OPENVDB=1 -DSLIC3R_NO_OPENCV=1 ${EXTRA_CXX_FLAGS}" \
  "-DCMAKE_C_FLAGS=-I${COMMON_SHIM_DIR} -I${TBB_INCLUDE_DIR} ${EXTRA_CXX_FLAGS}"

)

# ══════════════════════════════════════════════════════════
# Build WASM module
# ══════════════════════════════════════════════════════════
(
source "$EMSDK/emsdk_env.sh"
emmake cmake --build orca-wasm/build-wasm --target slicer -j4
echo "--- ccache stats ---"
ccache -s || true

)

# ══════════════════════════════════════════════════════════
# Package WASM artifacts
# ══════════════════════════════════════════════════════════
(
echo "--- build output ---"
ls -lh orca-wasm/build-wasm/wasm/ 2>/dev/null || ls -lh orca-wasm/build-wasm/ || true
echo "--- public/wasm/ ---"
ls -lh public/wasm/ 2>/dev/null || true

# Fallback copy if POST_BUILD didn't run.  ${OUTPUT_NAME}.data only
# exists when a --preload-file bundle is used; the v2.4.2 engine
# has none, so it is copied only if present.
BUILDDIR="orca-wasm/build-wasm/wasm"
if [[ ! -f "public/wasm/${OUTPUT_NAME}.js" ]] && [[ -f "${BUILDDIR}/${OUTPUT_NAME}.js" ]]; then
  mkdir -p public/wasm
  cp "${BUILDDIR}/${OUTPUT_NAME}.js"   "public/wasm/${OUTPUT_NAME}.js"
  cp "${BUILDDIR}/${OUTPUT_NAME}.wasm" "public/wasm/${OUTPUT_NAME}.wasm"
  [[ -f "${BUILDDIR}/${OUTPUT_NAME}.data" ]] && cp "${BUILDDIR}/${OUTPUT_NAME}.data" "public/wasm/${OUTPUT_NAME}.data"
fi

mkdir -p wasm-artifacts
cp "public/wasm/${OUTPUT_NAME}.js"   wasm-artifacts/
cp "public/wasm/${OUTPUT_NAME}.wasm" wasm-artifacts/
[[ -f "public/wasm/${OUTPUT_NAME}.data" ]] && cp "public/wasm/${OUTPUT_NAME}.data" wasm-artifacts/
ls -lh wasm-artifacts/

)

# ══════════════════════════════════════════════════════════
# Smoke test WASM module
# ══════════════════════════════════════════════════════════
(
node orca-wasm/scripts/smoke-test.mjs --wasm-dir public/wasm --engine "${OUTPUT_NAME}"
)
